### ISSUE TITLE
string.gmatch Match Multiple

### ISSUE THREAD

**Issue by SimonArmstrong0** [neolithos/neolua#10]
Hi,

Neolua is brilliant, but I have hit a problem with gmatch.

I think there is an issue when gmatch is supposed to return multiple results.
You have a script here "NeoLua.Test/Lua/Runtime12.lua", which should show the issue.

("This is the code in the script")
```lua
local s = "from=world, to=Lua"
local i = 0;
for k, v in string.gmatch(s, "(%w+)=(%w+)") do
	print(k .. "=" .. v);
	i = i + 1;
end;
return i;
```
The Printed value is incorrect, it prints 
from=world=
to=Lua=

Instead of
from=world
to=Lua

It seems the first result is the only result ever returned, and this returns the who match instead of the value in brackets.

Is this a know issue?
Thanks
Simon

**Comment by neolithos** [comment]
Now it is known. I am only suprised that I did not get an email that you posted this issue.

**Comment by neolithos** [comment]
I noticed that I have trouble to use capture and group in the right way. Hopefully I get it now right?

**Comment by SimonArmstrong0** [comment]
Ah you probably didn't get an email because Github though I was a robot when I created the issue.

Tried the fix, works perfectly.

Thanks

**Comment by neolithos** [comment]
Hopefiully in all cases.
