### ISSUE TITLE
ArgumentException: FindDeclaredProperty for String.Chars, is not unique

### ISSUE THREAD

**Issue by Symbai** [neolithos/neolua#100]
NeoLua Version: 1.3.9

The example code below generates the following exception. Project is targeting .NET Core 3.0, installed SDK Version:   3.0.100-preview4-011223

```
System.TypeInitializationException: 'The type initializer for 'Neo.IronLua.Lua' threw an exception.'
Inner exception:
ArgumentException: FindDeclaredProperty for String.Chars, is not unique.
```

Example to reproduce:
```
class Blub
{
private readonly Neo.IronLua.Lua lua = new Neo.IronLua.Lua();
}
....
var blub = new Blub();
```

//edit: It raises the exception at Lua.Binder.cs line 590:

`private readonly Dictionary<ExpressionType, CallSiteBinder> operationBinder = new Dictionary<ExpressionType, CallSiteBinder>();`

**Comment by neolithos** [comment]
The issue is in line Lua.Binder.cs:282, I made the member description more explicit. Currently, I can not test against this prerelease.

**Comment by Symbai** [comment]
It fixes it in my case, the exception is gone. Do you mind to bump the nuget version so I can switch back to nuget?

**Comment by neolithos** [comment]
I pushed a 1.3.10.0-beta.1...
