### ISSUE TITLE
Get wrong line while debugging a file loaded with dofile or require

### ISSUE THREAD

**Issue by felixbrose** [neolithos/neolua#101]
NeoLua Version: 1.3.10

If i load a lua file with "dofile" or "require" which produces a runtime error, the debugger only prints the line number of the "dofile" call, not the wrong line inside the loaded script.
Currently the only possible solution for debugging is to insert tons of "print" commands finding the wrong line.

Maybe its because "dofile" and "require" end up in DoChunk calling CompileChunk with null for LuaCompileOptions.

Is it somehow possible to retrieve the line number?

**Comment by neolithos** [comment]
That is correct. This parameter is responsible for the debug features.

Do you have a smart idea for nice option, to activate debugging for "dofile"?

Btw. I currently have override the "require" implementation in my own project. Do support more than files and debugging.

**Comment by felixbrose** [comment]
I have no idea yet.
Currently I had no luck compiling NeoLus myself. I'm using VS 2017. When I have time left I try to find a solution.

**Comment by neolithos** [comment]
Normally, this should be no problem, I use vs2017 also and the project should not have special dependencies. May you should unload all other projects in the solution.

May be I get some time on the weekend, to look into the problem more deeply.

**Comment by felixbrose** [comment]
I have updated to the newest version 1.3.11 and a short test looks promising. Nice work. File name and line is now reported for an "Object is nil" error within a file executed with dofile.

**Comment by neolithos** [comment]
Good to know.
