### ISSUE TITLE
Failed to parse Lua with clr variable as a name

### ISSUE THREAD

**Issue by sibvic** [neolithos/neolua#103]
NeoLua Version:
1.3.10

Example to reproduce:
```
local clr = 0;
function Func()
    clr = 1;
end
```

If you dochunk this peice of code you wil get LuaParseException "Expression is not assignable.". Does NeoLua forbids to use "clr" as a variable name? clr is a common short verion of color and I do have a lot of scripts containing it. Should I just regexp replace it to something else on loading? Or is it a bug?

**Comment by neolithos** [comment]
Clr is a special entrance to the .net framework. And it is not assignable. It is the only keyword I added to the language syntax.

**Comment by sibvic** [comment]
Maybe it's work to check code for clr inside dochunk? Or, at least, it's should be added into the documentation.

**Comment by neolithos** [comment]
[See Documentation](https://github.com/neolithos/neolua/blob/master/doc/05_01_clr.md)

Can you be more clear on the first question?

**Comment by sibvic** [comment]
Oh... for some reasons I han't seen this document. I'll add some Lua code preproccessor to get rid of clr variable and other Lua code snippets not supported by the NeoLua. Thank you.
