### ISSUE TITLE
Neo.IronLua.Lua throws exception in release mode

### ISSUE THREAD

**Issue by ilviio** [neolithos/neolua#104]
NeoLua Version: 1.3.10

We use NeuLua in an xamarin.android project to extend the functionality through a xml configuration file. Most of the Lua code seems to be pretty simple (convert timestamps to specific datetime formats or merge strings when a value has a specific value).

When we build the project in debug mode everything works fine but when we build in release mode we get the following error:

The type initializer for 'Neo.IronLua.Lua' threw an exception.;FindDeclaredMethod failed for Object.ReferenceEquals.  at Neo.IronLua.LuaEmit.GetOneResult[T] (System.Reflection.TypeInfo ti, System.String name, Neo.IronLua.ReflectionFlag flags, System.Collections.Generic.IEnumerable`1[T] list, System.String caller) [0x00059] in <a9cb0fd8da944861aef8645e3d7e85cf>:0

```
LuaType.RegisterTypeExtension(typeof(LuaLibraryString));
LuaType.RegisterTypeExtension(typeof(LuaLibraryMath));
LuaType.RegisterTypeExtension(typeof(LuaLibraryBit32));
LuaType.RegisterTypeExtension(typeof(TransformFunctions));
LuaType.RegisterTypeExtension(typeof(Constants));
LuaType.RegisterTypeExtension(typeof(ConfigurationParameters));

var luaCode = new Lua();
LuaGlobal g = luaCode.CreateEnvironment();
LuaResult result = g.DoChunk(lCode, "qpda", new KeyValuePair<string, object>("storageInput", stepInput));

return result.ToString();
```

This is (for example) one of our lua snippets:
storageInput:GetValue(); is a function in one of our C# libraries which simply returns the count of stored images in our storage

```
local val = storageInput:GetValue();

if val == 1 then
return " Bild";
elseif val > 1 then
return " Bilder";
end
```

**Comment by neolithos** [comment]
The exception says, that some method/property/menber can not be find.

The inner exception can give a hint, what is missing in release mode. Do have it?

**Comment by ilviio** [comment]
Hi @neolithos ,

This is an output from all inner exceptions

First Exception
The type initializer for 'Neo.IronLua.Lua' threw an exception.
StackTrace:   
at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
at Qpda.Components.Storage.TransformFunctions.LuaCode (Qpda.Components.Storage.IStorageItem stepInput, System.String lCode) [0x0005a] in <5b693be90f8b4a01abff97ed5e21d397>:0

InnerException: FindDeclaredMethod failed for Object.ReferenceEquals.
StackTrace:   
at Neo.IronLua.LuaEmit.GetOneResult[T] (System.Reflection.TypeInfo ti, System.String name, Neo.IronLua.ReflectionFlag flags, System.Collections.Generic.IEnumerable`1[T] list, System.String caller) [0x00059] in <a9cb0fd8da944861aef8645e3d7e85cf>:0
at Neo.IronLua.LuaEmit.FindDeclaredMethod (System.Reflection.TypeInfo ti, System.String sName, Neo.IronLua.ReflectionFlag flags, System.Type[] arguments) [0x00085] in <a9cb0fd8da944861aef8645e3d7e85cf>:0
at Neo.IronLua.Lua..cctor () [0x00ab9] in <a9cb0fd8da944861aef8645e3d7e85cf>:0

**Comment by neolithos** [comment]
It looks that you try compile native code, this seems not be supported by the reflection library. Lua can not locate Object.ReferenceEquals.

**Comment by ilviio** [comment]
Thx for the hint,

Problem lies in the linker settings
We have set the Linking Option to "Sdk Assemblies Only"

After we added "mscorlib" to "Skip linking assemblies" everything works fine now.
