### ISSUE TITLE
How to interrupt execution?

### ISSUE THREAD

**Issue by PatrickKursawe** [neolithos/neolua#106]
Did I miss something, or is there no way to interrupt the execution of a Lua chunk? Nothing like a CancellationToken or similar that is checked? I just managed to write an infinite loop by accident and noticed that I didn't yet cover this case in my application.
Thank you for any hints!

**Comment by neolithos** [comment]
There is no build in. But you can create your own chunks with the debug interface and implement such functionality.

https://github.com/neolithos/neolua/blob/06294ba377401e6f48938d828cddb1efe5b69d8b/NeoLua/LuaDebug.cs#L51-L59

**Comment by PatrickKursawe** [comment]
Thank you. Will check this out, have something more urgent on the plate right now (as usual).

**Comment by neolithos** [comment]
Okay. If you have question to this topic let me known. Btw. in the same file is an example, how to use this interface.
