### ISSUE TITLE
Questions about events

### ISSUE THREAD

**Issue by Symbai** [neolithos/neolua#108]
I would like to add events from C# which can be called in LUA. I've seen this https://github.com/neolithos/neolua/blob/91ef37dd8fe790b9a86f3a2e1e8c9cd62a5e757a/doc/05_01_clr.md#events but still have a few questions.

1. How does the lua environment / script gets aware of the "EventTest" event? Shouldn't it be somehow added it to the environment first?!
2. Is it possible to get rid of the namespace and make the script be able to call "EventTest" directly without "myClass." ?
3. Are there any complete examples about events?

**Comment by neolithos** [comment]
What do you want to write? May be I can give a little help.

#### to 1
EventTest is declared on a .net class in c#.

#### to 2
Currently, events can only declared on pure .net classes. Because, all events are internal converted to `LuaEvent` ([Link](https://github.com/neolithos/neolua/blob/dc51fecfe841c62e5fd24d5519e0af936cd852e6/NeoLua/LuaType.cs#L2191)) and need a none dynamic type.

#### to 3
Nobody ask me, before you. So the answer is no.

**Comment by Symbai** [comment]
@neolithos: Something like this:

### C#
```
Neo.IronLua.Lua lua = new Neo.IronLua.Lua();

public Action SomethingHappened;

public void Bla() {
	dynamic dg = lua.CreateEnvironment();
	dg.SomethingHappend = SomethingHappened; //??!!
}
public void RaiseEvent() {
SomethingHappened?.Invoke()
}
```
### Lua
And later a script I load can listen to it:
```
function SomethingHappened()
print('woohoo')
end
```

**Comment by neolithos** [comment]
For this I use the following pattern:
```C#

private LuaTable g;

public void Bla() {
	dynamic dg = g = lua.CreateEnvironment();
}
public void RaiseEvent() {
	g.CallMemberDirect("SomethingHappened", null, ignoreNilFunction: true);
}
```

**Comment by Symbai** [comment]
Does this work in all cases or would it cause issues / exceptions when there are two different scripts and BOTH listen to `SomethingHappened` and BOTH needed to be called? Otherwise it seems to be fine for my purpose.

**Comment by neolithos** [comment]
If you have a new instance of the environment, there is no problem.
Do want to use the same instance of the environment. The script needs to take care.

**Comment by Symbai** [comment]
Yes. I create one lua environment on application start. And plan to add user scripts which were using this environment. User scripts should be able to register to certain events which I then raise in my C# app and each script which listens to it execute its code.

So lua scripts become plugins.

**Comment by neolithos** [comment]
You should create a LuaTable for every script in this case... So, the scripts are isolated...

Example:
```C#
public class ScriptHost : LuaTable
{
  private LuaGlobal g;

public override object OnIndex(object key)
  => g[key];

public void RaiseEvent() {
	g.CallMemberDirect("SomethingHappened", null, ignoreNilFunction: true);
}
}
```

**Comment by Symbai** [comment]
This is what you normally do yes but I don't want to isolate scripts (because I don't run any code where security matters). Otherwise every time I update a variable or raise an event I would have to iterate through every script and do that. I would also have to register all >100 functions for every script, this seems to be an overkill.

I thought/expected it to work like in C#. You create a single class with a single event and invoke it and every listener gets automatically invoked. Like in my example above.

**Comment by neolithos** [comment]
That has nothing to do with security. Is just separating names.

Lua has no concept of events in first place. You need to create your own list. You can also overload the `OnNewIndex`-Method to create your event lists. That will also support your proposed syntax.

```C#

public override bool OnNewIndex(object key, object value)
{
  if (key is string member)
  {
    switch(member)
    { 
      case "SomethingHappened":
          AddEvent(value);
...
```
But events are also list, that are iterated.

**Comment by Symbai** [comment]
Okay I guess there is no workaround or it doesn't work the way I thought it would. I will follow your advice and isolate the script then, thanks.
