### ISSUE TITLE
Unexpected token 'const'

### ISSUE THREAD

**Issue by RussellHaley** [neolithos/neolua#109]
NeoLua Version: 1.3.11

Hi, I see you ave a jump on implementing 5.4? The error I am seeing is in a much longer script, but this simple example reproduces it. I'm sure your aware const is not an actual reserved word in 5.4 (that must be a nightmare to parse?).

Example to reproduce:
```C#
static void Main(string[] args)
        {
            Lua L = new Lua();
            var g = L.CreateEnvironment();
            g.DoChunk(@"t = {}
t.test = 1
t.const = false
print t.const", "c1");
        }
```

**Comment by neolithos** [comment]
I defined "const" as a keyword to make the handling with clr-types a little bit easier ([doc](https://github.com/neolithos/neolua/blob/master/doc/03_language.md#keyword-const)).

I will fix this, that members can be named const.

As a work around, you can replace it with `t["const"]`.

**Comment by neolithos** [comment]
Do you need a quick new version?

**Comment by RussellHaley** [comment]
No, I can build from source if needed. Keep being awesome!
