### ISSUE TITLE
TranslateRegularExpression function corrections

### ISSUE THREAD

**Issue by SimonArmstrong0** [neolithos/neolua#11]
Hi,

Using the new improved gmatch, I have noticed a couple of issues with the TranslateRegularExpression. There were a couple of typos and some of the translations looked incorrect.
I have gone through and changed them to what I believe to be correct. I has also added the uppercase variations that do the opposite of the lower case chars. 
From  http://www.lua.org/manual/5.3/manual.html "For all classes represented by single letters (%a, %c, etc.), the corresponding uppercase letter represents the complement of the class. For instance, %S represents all non-space characters."

Hope this helps.
```c#
case 'a': // all letters
	sb.Append("\\p{L}");
	break;
case 'A': // all Non letters
	sb.Append("\\P{L}");
	break;								
case 's': // all space characters
	sb.Append("\\s");
	break;
case 'S': // all NON space characters
	sb.Append("\\S");
	break;	
case 'd': // all digits
	sb.Append("\\d");
	break;
case 'D': // all NON digits
	sb.Append("\\D");
	break;								
case 'w': // all alphanumeric characters
	sb.Append("\\w");
	break;
case 'W': // all NON alphanumeric characters
	sb.Append("\\W");
	break;								
case 'c': // all control characters
	sb.Append("\\p{C}");
	break;
case 'C': // all NON control characters
	sb.Append("\\P{C}");
	break;								
case 'g': // all printable characters except space
	sb.Append("\\S");
	break;
case 'G': // all NON printable characters including space
	sb.Append("\\s");
	break;								
case 'p': // all punctuation characters
	sb.Append("\\p{P}");
	break;
case 'P': // all NON punctuation characters
	sb.Append("\\P{P}");
	break;								
case 'l': // all lowercase letters
	sb.Append("\\p{Ll}");
	break;
case 'L': // all NON lowercase letters
	sb.Append("\\P{Ll}");
	break;								
case 'u': // all uppercase letters
	sb.Append("\\p{Lu}");
	break;
case 'U': // all NON uppercase letters
	sb.Append("\\P{Lu}");
	break;								
case 'x': // all hexadecimal digits
	sb.Append("\\[0-9A-Fa-f]");
	break;
case 'X': // all NON hexadecimal digits
	sb.Append("\\[^0-9A-Fa-f]");
	break;
```

Simon

**Comment by neolithos** [comment]
There was a typo.
And I changed the translation for g.

Is this ok? If you say yes, I will port the changes to the master branch.

**Comment by SimonArmstrong0** [comment]
Yes you are Correct, %g needs to the \p{C} as well.
I though it was just to opposite of %s, but you are right it also has to ignore special chars.
