### ISSUE TITLE
Fixd Bug  public Project : Tree<Project>{}  LuaType.cs  throw a error : stackoverflow!

### ISSUE THREAD

**Issue by snow-li-2019** [neolithos/neolua#124]
NeoLua Version: 1.3.11

// I defind class
public  class Project : Tree<'Project'>
{
}

//running 
LuaType.cs throw a error : stackoverflow!

//source:
       private bool SetType(Type type)
        {
            if (type == null)
                return false;
            else
            {
                var typeInfo = type.GetTypeInfo();

                if (typeInfo.IsGenericTypeDefinition) // it is only a type definition
                    return false;
                else
                {
                    // set the value
                    this.type = type;

                    //update the base type
                    baseType = typeInfo.BaseType == null ? null : GetType(typeInfo.BaseType);

                    // update known types
                    lock (knownTypes)
                    {
                        knownTypes[type] =
                            knownTypeStrings[fullName] = GetTypeIndex(this); // update type cache
                    }

                    // update implemented types
                    implementedInterfaces = new Lazy<LuaType[]>(() => (from c in typeInfo.ImplementedInterfaces select GetType(c)).ToArray(), true);
                }

                return true;
            }
        } // proc SetType

// I fixed :
       private bool SetType(Type type)
        {
            if (type == null)
                return false;
            else
            {
                var typeInfo = type.GetTypeInfo();

                if (typeInfo.IsGenericTypeDefinition) // it is only a type definition
                    return false;
                else
                {
                    // set the value
                    this.type = type;

                    // update known types
                    lock (knownTypes)
                    {
                        if (knownTypes.ContainsKey(type)) return true;//  fix 修复

                        knownTypes[type] =
                            knownTypeStrings[fullName] = GetTypeIndex(this); // update type cache
                    }

                    // fix 修复 update the base type
                    baseType = typeInfo.BaseType == null ? null : GetType(typeInfo.BaseType);

                    // update implemented types
                    implementedInterfaces = new Lazy<LuaType[]>(() => (from c in typeInfo.ImplementedInterfaces select GetType(c)).ToArray(), true);
                }

                return true;
            }
        } // proc SetType

**Comment by neolithos** [comment]
Why did you add the test?

```C#
if (knownTypes.ContainsKey(type)) return true;
```

This should not needed.

**Comment by snow-li-2019** [comment]
Fast Interrupt loop!

**Comment by snow-li-2019** [comment]
How long？ .NET5.0 and Lua5.4

**Comment by neolithos** [comment]
> Fast Interrupt loop!

I do not understand?

> How long？ .NET5.0 and Lua5.4

- .net 5.0 should be easy to do. It is only an additional parameter in the cs-project file. I testet neolua with a .net 5.0 project, and I didn't need any changes to the nuget package?

- Lua5.4, two features need to be implemented (#113, #114); this will take a little bit longer for me. If you need them really quick, you can do an official request to my company.

**Comment by snow-li-2019** [comment]
Thank you for your prompt reply!
1.  "Fast Interrupt loop!" I mean to say,GetType() is iterative process,A termination condition is required,"if (knownTypes.ContainsKey(type)) return true;" is a Fast Interrupt  condition.
2.  " .NET5.0"  I mean to say,open vs2017 set <TargetFramework>net5.0</TargetFramework> and <Nullable>enable</Nullable> ,the Null Warning message anywhere，I like to be clean and tidy。
 3. Lua5.4  I mean to say,I love neolua.

**Comment by neolithos** [comment]
1. I will check this, the question is, how expensive is this lookup.
2. I am afraid ;). I tent also to clean up these warnings. May at weekend will see how much it is.
3. Thx.

**Comment by snow-li-2019** [comment]
1.It took me a week to discover the problem.
2.Thx.
3.Thx.

**Comment by neolithos** [comment]
1. That is good. This part is complex. I am still on it.
2. I added net5.0 as target, but since I need to support for .net 4.5. I can not change anything. Or I have no glue how.
