### ISSUE TITLE
Read Stdout stream after running chunk - Documentation?

### ISSUE THREAD

**Issue by ShadowMarker789** [neolithos/neolua#125]
NeoLua Version: Nuget 1.3.11

Example to reproduce:
```Lua
io.write('this is a string\n'); 
print('this is another string. I am creative');
``` 

After reading the documentation, there's no mention of how to read the Stdout of the Lua runtime. 

There's a protected member of LuaGlobal `OnPrint` but that's not mentioned in the documentation either. 

If I just want a string that's the concatenation of all calls to io.write or print how would I best get that?

**Comment by ShadowMarker789** [comment]
The below code-chunk will do something LIKE that, but this is not what I envisioned. 

![image](https://user-images.githubusercontent.com/37165910/109826589-e7fbf880-7c75-11eb-8b30-9ce613c99389.png)

🤔

**Comment by neolithos** [comment]
On default all is redirected to the console window. That is not what you want.

This seems to be a wpf application. So it might be the best, to override `LuaGlobal` and `OnPrint`. And call on IO `input`, `output` to set a stream that catches all calls. A example for the file parameter is at:
https://github.com/neolithos/neolua/blob/c60d3a8e2e298f7b08e3c432d86796a1a264a5d7/NeoLua/LuaLibraries.cs#L1350-L1361

**Comment by yuppox** [comment]
I'm trying to do this as well, with a Forms app. Can you elaborate on how I can redirect `print` to a string or text control?

I'm not sure I understand how `LuaGlobal` is supposed to work. I normally create a `Lua` object and get an environment from that.

Thanks.

**Comment by neolithos** [comment]
The direct way I descriped is the best. It works on all application types.
