### ISSUE TITLE
Assigning to LuaMember bool or int

### ISSUE THREAD

**Issue by SimonArmstrong0** [neolithos/neolua#13]
Hi

I am having an issue assigning to bool and int from a lua script, I am not sure what the best solution is.

I have a c# class that inherits from LuaTable, so it can be treated like any other table in the Lua code.
This class has a few pre existing properties, which are defined in the class.

Such as
```c#
[LuaMember("DebugOn")]
public bool DebugOn
{
    get;
    set;
}
```

Getting the properties from bool and int work fine in the lua code.
```Lua
debugValue = object.DebugOn
```

But if I try to set a boolean or Int I get a dynamic binding exception
```Lua
object.DebugOn = false
```
"The result type 'System.Boolean' of the dynamic binding produced by the object with type 'Model.Protocols' for the binder 'Neo.IronLua.Lua+LuaSetMemberBinder' is not compatible with the result type 'System.Object' expected by the call site."

If I change to type to an object it works fine. But then I have to cast the value to what it should be.  Like so:
```c#
private bool debugOn;
[LuaMember("DebugOn")]
public bool DebugOn
{
    get { return debugOn;}
    set { debugOn = (bool)value; }
}
```

Is there a better way of doing this? Am I doing something wrong.

Thanks
Simon

**Comment by neolithos** [comment]
Can you give me the version your currently using?
It looks like a bug. I will check this after my vacation.

Greetings from the Mediterranean sea.

**Comment by SimonArmstrong0** [comment]
Hope your having a good Holiday! :smile:

Its with version 0.9.17

**Comment by neolithos** [comment]
I will drop the support for .net 4 in a couple of days and join the portable branch with the master (sse #9).

Then there will be a compiled version of the library.

Any complaints, let me know :) ?

**Comment by SimonArmstrong0** [comment]
4.5.1 is fine with me.

**Comment by neolithos** [comment]
Branch merged a new beta-version will be coming soon.
