### ISSUE TITLE
NeoLua without DLL (static / embedded in C#)

### ISSUE THREAD

**Issue by yuppox** [neolithos/neolua#130]
NeoLua Version: 5.3

If I wanted to "embed" this in a C# application, would it be difficult to import the code, rather than requiring a DLL?

It seems to depend on a "Resources.resx" file. Are there other things it would need?

**Comment by neolithos** [comment]
I always use the nuget package for my projects.

But there are tools for .net to pack all assemblies in one pe-file. Maybe this is easier. But I never tried.

**Comment by PatrickKursawe** [comment]
Not actively using it, but this here:
https://github.com/Fody/Costura
could do the trick for @yuppox .
