### ISSUE TITLE
Issues using table.insert ?

### ISSUE THREAD

**Issue by jesusgumbau** [neolithos/neolua#131]
NeoLua Version: 1.3.13

Hi, I am having issues trying to write a Lua function that copies the list apssed as parameter.

This doesn't seem to work:
```Lua
function copy(list)
	-- Copy the input list
	local copy = {}
	foreach item in list do
		table.insert(copy, item)
	end
	return copy
end
```
But This works as expected:
```Lua
function copy(list)
	-- Copy the input list
	local copy = {}
	copy = list
	return copy
end
```

I tried require("table") but still not working.
Any ideas?

**Comment by neolithos** [comment]
Both code blocks will not do what you want: http://lua-users.org/wiki/CopyTable

**Comment by jesusgumbau** [comment]
True, but I didn't want to do a deep copy. Just have 2 tables containing the same elements.

Shoudn't in both cases the function return a table populated with elements? I don't seem to get it with the first block of code.

**Comment by neolithos** [comment]
May be this is what you looking for:
```Lua
for k,v in pairs(t) do
   c[k] = v;
end;
```
This short snippet copies all members. You can filter the key `k`.

Less memory consuming would be to use metatables.


For an easy deep copy, there is also:
```Lua
table.merge
```
