### ISSUE TITLE
Problem with using C# UInt32 variable as a lua table key ("No conversion defined from UInt32 to indexKey")

### ISSUE THREAD

**Issue by Nevlabs** [neolithos/neolua#134]
NeoLua Version:
1.3.13
Example to reproduce:
uint key = 2;
var code = @"
  local tbl = {}
  tbl[key] = 5
  return tbl[key]";

var lua = new Lua();
dynamic env = lua.CreateEnvironment<LuaGlobal>();
env.key = key;
var chunk = lua.CompileChunk(code, "lua.lua", new LuaCompileOptions());
var r = env.dochunk(chunk);

Works fine if key type would be int or ushort.

**Comment by neolithos** [comment]
The array part of the lua table is only design for integer. All types that are fit in an integer are okay. UInt32, UInt64 and Int64 are an problem and will result in exceptions.

I did a little fix. Now it works, but it will result in endless loops?
I need more test cases for these part.

**Comment by neolithos** [comment]
No, it should work as intented.
