### ISSUE TITLE
ToJson creates invalid Json when encoding +/- infinity

### ISSUE THREAD

**Issue by thoj** [neolithos/neolua#135]
NeoLua Version: latest

Example to reproduce:
Json output if there is a Infinity number:
```
{
 "test1": 0.0,
 "test2": -Infinity.0
}
```
Not a huge issue, and easily worked around, but the application consuming this crashed spectacularly. hehe.

https://www.ietf.org/rfc/rfc4627.txt (2.4)

"Numeric values that cannot be represented as sequences of digits (such as Infinity and NaN) are not permitted."

Not sure how to handle this properly. My suggestion would be just to use the string "-/+Infinity" instead.

**Comment by neolithos** [comment]
Another solution might be, to emit a "nil"?
