### ISSUE TITLE
.Net 6 - Assembly.ReflectionOnlyLoad always throws exceptions for your classes

### ISSUE THREAD

**Issue by ShadowMarker789** [neolithos/neolua#142]
NeoLua Version: 1.3.14 from NuGet  - BUT ERROR ONLY IN .NET 6! 

Example to reproduce:
( Lua code that interacts with your own custom classes )
```lua
AddChoice = clr.Blithe.VisualNovel.Instance.AddChoice; 
AddChoice("Yes", YesToBeingAHero, true);
```

Unfortunately Assembly.ReflectionOnlyLoad was obsoleted in .Net 6 as per [Microsoft Documentation](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.reflectiononlyload?view=net-6.0#System_Reflection_Assembly_ReflectionOnlyLoad_System_String_)

As a result [This Line of Code](https://github.com/neolithos/neolua/blob/master/NeoLua/LuaType.cs#L1074) always throws an exception on this platform. 

Could we perhaps get a platform or runtime check for .Net 6?

**Comment by ShadowMarker789** [comment]
I had just recently upgraded my game project to .Net 6 since I wanted to use certain libraries that only work in .Net 6 - turns out the upgrade caused problems for NeoLua.

**Comment by ShadowMarker789** [comment]
As it happens if you ignore those exceptions thrown everything continues to work but while it's busy throwing an exception for every assembly loaded we're eating a lot of overhead as a result from the exception unrolling and stack-trace.

**Comment by ShadowMarker789** [comment]
Did some testing by cloning and modifying. 

Pull request created: [Bugfix Pull Request](https://github.com/neolithos/neolua/pull/143)

**Comment by Whoome** [comment]
Nevermind, I see it, there was a missing conditional
