### ISSUE TITLE
Passing an argument by reference

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [neolithos/neolua#157]
Does NeoLua support Passing by reference like in C#? I mean:
```csharp
void ChangeValue(ref int arg) {
    arg = 1;
}
```
Can this function be implemented in NeoLua, for example:
```lua
function ChangeValue(ref arg: int): void
    arg = 1
end
```
The motivation is that I want to use NeoLua with the [Harmony](https://github.com/pardeike/Harmony) library for game modding.

**Comment by neolithos** [comment]
No, Lua has multiple return values. if a .net function uses ref parameters, they will be mapped to a result value.

```C#
void Test(ref int a);
```
```Lua
local r = Test(1);
```

**Comment by Meigyoku-Thmn** [comment]
Thanks, guess I have to use DynamicMethod as a wrapper for this functionality.
