### ISSUE TITLE
Range character classes in regexp work incorrectly

### ISSUE THREAD

**Issue by hdkeeper** [neolithos/neolua#18]
Character classes with range in regexp work incorrectly in NeoLua.

C Lua sample:
```lua
local r = string.gsub("192.168.33.15", '[0-9]+', "x");
print(r);
-- prints x.x.x.x -> ok
```

NeoLua sample
```lua
form.testBox.Text = string.gsub("192.168.33.15", '[0-9]+', "x");
-- prints 1x2.168.33.15 -> ERROR
```

Although if you set ```string.__TranslateRegEx = true```, it works fine again.
Is there a bug in regexp translator?

**Comment by neolithos** [comment]
Yes, it was :).

Thx for reporting.
