### ISSUE TITLE
Incorrect CLR namespace resolving

### ISSUE THREAD

**Issue by hdkeeper** [neolithos/neolua#25]
I'm trying to use MySQL .NET connector. It seems like namespaces are resolved incorrectly.
```lua
clr.System.Windows.Forms.MessageBox:Show('{0}':Format(clr.MySql.Data));
-- Outputs MySql.Data - correct

clr.System.Windows.Forms.MessageBox:Show('{0}':Format(clr.System.Data));
-- Outputs MySql.Data again - incorrect!
```

Because of this, I cannot create an instance of System.Data.DataTable.
```lua
local eventTable = clr.System.Data.DataTable();
-- Raises "Object is null" exception
```

**Comment by neolithos** [comment]
I know this issue.
And I think I solved it at https://github.com/neolithos/neolua/commit/602a2a53b42efb6805e47f0e31b2be35c2a758f5.

Do you a have a version number for me?
Or a other example?

**Comment by hdkeeper** [comment]
Version is last for today.
https://github.com/neolithos/neolua/commit/fa51d12cd78de11c4707d3aaff3058501e431633

Here's another example:
```lua
clr.System.Windows.Forms.MessageBox:Show('{0} {1}':Format( 
    clr.System.Windows, clr.Microsoft.Windows));
-- Outputs System.Windows System.Windows - WTF?
```

**Comment by neolithos** [comment]
Thanks for the example. I created a new test case for this issue.

I currently, thinking about a total redesign of the type interface, so this test will very helpful, that I not run in this issue again.

**Comment by hdkeeper** [comment]
Thank you! Now it works.
