### ISSUE TITLE
Overload resolution issue on NeoLua 1.1.1

### ISSUE THREAD

**Issue by nta** [neolithos/neolua#26]
```
NeoLua Interactive Command
Version NeoLua 5.3 (1.1.1.0) by neolithos

  source code at http://neolua.codeplex.com
  supported from http://tecware-gmbh.de

  Write ':h' for help.

> utf8 = clr.System.Text.Encoding.UTF8
> utf8:GetBytes('hi')
>
ArgumentNullException: Array cannot be null.
Parameter name: bytes
 at line(LuaTable _G) line line:2:1
```

It seems (from the stack trace in my actual application) it tries to call the UTF8Encoding.GetBytes(String, Int32, Int32, Byte[], Int32) overload, rather than GetBytes(String) as requested.

**Comment by neolithos** [comment]
It is hard to implement a good overloading for a dynamic language :(.

Hope I fixed it.

**Comment by ggDanDev** [comment]
I'm having problems with overloads. I'm using the latest commit (acf9ec4).

If I declare the parameters as variables (r1), it runs, but otherwise I get an exception.
Using constructors (r2), I get "Specified cast is not valid.".
Using methods (r3), I get "No conversion defined from Vector3 to Single.".

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Neo.IronLua;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            var lua = new Lua();
            var global = new LuaGlobalPortable(lua);

            global.RegisterPackage("CFrame", typeof(CFrame));
            global.RegisterPackage("Vector3", typeof(Vector3));

            var r1 = global.DoChunk("local v = Vector3(1, 2, 3); return CFrame(v, v)", "Test.lua");
            var r2 = global.DoChunk("return CFrame(Vector3(1, 2, 3), Vector3(1, 2, 3))", "Test.lua");
            var r3 = global.DoChunk("return CFrame.new(Vector3.new(1, 2, 3), Vector3.new(1, 2, 3))", "Test.lua");

            Console.WriteLine(r1.ToString());
            Console.WriteLine(r2.ToString());
            Console.WriteLine(r3.ToString());

            Console.ReadKey();
        }
    }

    struct Vector3
    {
        public float x;
        public float y;
        public float z;

        public Vector3(float x, float y, float z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }

        public static Vector3 @new(float x, float y, float z)
        {
            return  new Vector3(x, y, z);
        }
    }

    struct CFrame
    {
        public float x;
        public float y;
        public float z;

        public CFrame(float x, float y, float z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }

        public CFrame(Vector3 v0, Vector3 v1)
        {
            this.x = v0.x + v1.x;
            this.y = v0.y + v1.y;
            this.z = v0.z + v1.z;
        }

        public static CFrame @new(float x, float y, float z)
        {
            return new CFrame(x, y, z);
        }

        public static CFrame @new(Vector3 v0, Vector3 v1)
        {
            return new CFrame(v0, v1);
        }
    }
}
```

**Comment by neolithos** [comment]
The result is as proposed.

What is going on in this example:
```Lua
return CFrame(Vector3(1, 2, 3), Vector3(1, 2, 3))
```

Every function called in Lua returns a LuaResult (because of the missing "out/ref" concept). So, the type system try to find an overload, that looks like (with the positional algorithm, because there are no argument names):
```
Call: Neo.IronLua.LuaResult, Neo.IronLua.LuaResult
```
Defined are two overloads (with the score):
```
Reset member: Void .ctor(Single, Single, Single)
      Result: OnBegin=0, Exact=0, Implicit=0, Explicit=2147483647, ParameterLength=3
Reset member: Void .ctor(ExtTest.Vector3, ExtTest.Vector3)
      Result: OnBegin=0, Exact=0, Implicit=0, Explicit=2147483647, ParameterLength=2 
```
The first one, gets the highest score, because of the parameter length:
```
USED: Void .ctor(Single, Single, Single)
```
Run the library as a debug version and you will see the same output.

What can you do, to solve the problem:

1. Set brackets to cast the return value to an object (or use the cast keyword):
```Lua
return CFrame((Vector3(1, 2, 3)), (Vector3(1, 2, 3)))
```
2. Use named parameters:
```Lua
return CFrame(v0=Vector3(1, 2, 3)), v1=Vector3(1, 2, 3))
```
3. Give me an idea to solve the problem, because in the most cases it is a good solution. Example:
```Lua
function test() return "{0} + {1} = {2}", 40, 2, 42; end;
return clr.System.String.Format(test())
```

Hope, I did explain it properly.

**Comment by ggDanDev** [comment]
Why does (Single, Single, Single) get the highest score because of it's length if it's 3 params when the call is 2 params? Should it not guess the one which is equal length?

**Comment by neolithos** [comment]
That is the point, the call in Lua has infinite parameters (not two), because the return value of a function can have infinite values.

If you embrace the last parameter, it count's as one. Or you can use named arguments.

There are two worlds crossing ... the current way I thing, is the best to combine. May be you have a better solution? Feel free to try.

**Comment by ggDanDev** [comment]
I messed about with the "FindMember" function. The length of "TARG[] arguments" seems to be the same number of parameters written in the lua script, but I noticed that using that tuples only pass one LuaResultMetaObject, whose value seems to be a collection.

```lua
-- tuple return
function test()
    return 1, 2, 3, 4, 5, 6
end
return CFrame.new(test())
```

I'm never going to have more than one overload use the same number of arguments. (although that probably won't apply to others)

What should I change to guarantee that the overload with the exact same number of arguments is picked, while also accounting for tuples?

**Comment by neolithos** [comment]
In LuaEmit.cs:2263
```C#
var unboundedArguments = callInfo.ArgumentNames.Count == 0 && arguments.Length > 0 ? getType(arguments[arguments.Length - 1]) == typeof(LuaResult) : false;
```
UnboundedArguments should be set to false. This will use always the first argument of the LuaResult.

But this will also break code like:
```Lua
function test() return "{0} + {1} = {2}", 40, 2, 42; end;
return clr.System.String.Format(test())
```

**Comment by ggDanDev** [comment]
The unboundedArguments didn't seem to work, so I decided to replace the body of FindMember with this:

```c#

		    while (memberEnum.MoveNext())
		    {
		        var cur = memberEnum.Current;
		        var paramaters = MemberMatch<TMembertype, TArg>.GetMemberParameter(cur, isMemberCall);

		        if (paramaters.Length == arguments.Length)
		        {
		            pickedMember = cur;
		        }
		    }

		    if (pickedMember == null)
		    {
		        var msg = $"Invalid number of arguments: {arguments.Length}";

                throw new LuaRuntimeException(msg, new ArgumentOutOfRangeException(msg));
		    }

		    return pickedMember;

```

This seems to work fine, except for tuples like this:
```lua
function test()
    return Vector3.new(1, 2, 3), Vector3.new(1, 2, 3)
end
local cf = CFrame(test())
```

As I said earlier, this only passes a single LuaResultMetaObject in the arguments array.

I tried using `GetType()` on the `Value` property of LuaResultMetaObject, which seems to just return the Vector3 type. But if I hover over the value in a breakpoint, it seems to be a collection.

![image](https://cloud.githubusercontent.com/assets/14797394/12511301/30fd2dbc-c108-11e5-9af0-4a1c30c86488.png)

Trying to access the 'Values' property throws `'System.ValueType' does not contain a definition for 'Values'`

How could I count the number of values that a tuple return contains?

**Comment by neolithos** [comment]
LuaResult returns both a collection and a single values. This is defined in dymaic binder. Use explicit cast to turn of the dynamic interface.

For what you try to do, you should dive into DLR a little bit deeper. It will only work on one call, on a equal call with the same LuaResult but different values, it will fail.

FindMember is called from two sites, one site is the parser. And the other one is the DLR (LuaType, LuaMemberBinder, LuaResult, ...)

Steps to solve your problem (maybe):
- In LuaType, MemberBind: LuaResult as last parameter, choose a diffrent restriction (include number of results, and maybe types, this is important)
- Add ParameterInfo's for the result (only in positial mode)

Hope, this pushes you in the correct direction? If you want, send me a diff, and I will see if your solution is correct (as far I can see).

**Comment by ggDanDev** [comment]
>In LuaType, MemberBind: LuaResult as last parameter, choose a diffrent restriction (include number of results, and maybe types, this is important)

Sorry, I don't have much experience with the DLR (and it seems to be hard to google) - how do restrictions work? It looks like I need to use `BindingRestrictions.GetExpressionRestriction()` with a custom expression. Does the expression get invoked on each LuaResult?

**Comment by ggDanDev** [comment]
I've made an expression like this:
```c#
private BindingRestrictions GetNumberOfResultsRestriction(int argumentCount)
		    {
		        return BindingRestrictions.GetExpressionRestriction(
		            Expression.Equal(
		                Expression.Property(
		                        Expression.Property(Expression, Lua.ResultValuesPropertyInfo),
		                        Lua.ListCountPropertyInfo
                            ),
                        Expression.Constant(argumentCount)
		                )
		            );
		    }
```
(I assume `Lua.ListCountPropertyInfo` is the wrong property but I haven't tested it yet)

Am I supposed add this restriction in `BindInvokeMember`? If I put a breakpoint on the method, it doesn't seem to be called.

**Comment by neolithos** [comment]
This is the right direction.

To get a feeling for the DLR, play a little with the Expression-class and the Compile-Method.
Secound, and this is the harder part, use DynamicExpression for a late compile.

Source:
https://dlr.codeplex.com/wikipage?title=Docs%20and%20specs&referringTitle=Documentation

First read:
https://www.codeplex.com/Download?ProjectName=dlr&DownloadId=127512
Then this:
https://www.codeplex.com/Download?ProjectName=dlr&DownloadId=127517
And the most interesting:
https://www.codeplex.com/Download?ProjectName=dlr&DownloadId=127518

**Comment by ggDanDev** [comment]
Thanks for the useful links.
When is BindInvokeMember usually supposed to be called?

**Comment by neolithos** [comment]
Short answer: It is called within DynamicExpression or the CallSite that is created.
It is a quiet interesting topic, and really useful to learn.




And I still hope, that someone can contribute parts to the project, to make better and better.

**Comment by ggDanDev** [comment]
So `BindInvokeMember` is called after `FindMember`? How would I determine which member FindMember should return without already knowing the number of tuple values?

**Comment by neolithos** [comment]
No, FindMember will be called from BindInvokeMember.

But I had little bit time to thing about the problem. Trying to solve  the issue with LuaResult will create a mess of constraints and exceptions.
Better, it would be to support the Tuple<>'s.
I did not thing through until know, but this might be a solution...
