### ISSUE TITLE
Dynamic accessor

### ISSUE THREAD

**Issue by ggDanDev** [neolithos/neolua#29]
In my library, I have a class with a dictionary, and I want scripts to be able to directly access them, e.g myobject.ChildObject.DeeperChildObject.

I made the base class inherit from DynamicObject, and overrode ["TryGetMember"](https://msdn.microsoft.com/en-us/library/system.dynamic.dynamicobject.trygetmember(v=vs.110).aspx), but the method does not get invoked when accessing an object in the LuaGlobalTable. I was going to try inherit from LuaTable, but this causes issues with protobuf-net/serialization.

How could I achieve this with NeoLua?

**Comment by neolithos** [comment]
Do you have some code snippets?
Overall it sounds okay.

**Comment by ggDanDev** [comment]
Class snippets
```
public abstract class Instance : DynamicObject
{
        protected Dictionary<string, Instance> _children = new Dictionary<string, Instance>();

        public override bool TryGetMember(GetMemberBinder binder, out object result)
        {
            object value;

            if (_children.TryGetValue(binder.Name, out value))
            {
                result = value;
                return true;
            }

            return base.TryGetMember(binder, out result);
        }
}

public class Workspace : Instance
{
}
```
An instance of Workspace is added to the global table.

```
var global = new LuaGlobal(_lua)            
{
    ["workspace"] = new Workspace(),
};
```

**Comment by neolithos** [comment]
Hi, I know what is going on.
I did a small fix, but I will need more time to evaluate the problem.

Can you see, if the commit helps you?

**Comment by ggDanDev** [comment]
That works great! Thanks, that's really helpful.

**Comment by neolithos** [comment]
Becareful, I only checked GetMember.

**Comment by neolithos** [comment]
The branche "LuaTable" has the correct solution for this problem. If you want to check it out. But becareful, it was a big rewrite. And I am not finished, yet.

**Comment by neolithos** [comment]
This commit 91181eee5702dfdd5c12233d2cfabbf4909b7aa4 should solve your issue finally.

Can you give me feedback?
