### ISSUE TITLE
creating lambda with non existing property is possible when it should not be.

### ISSUE THREAD

**Issue by tschmit** [neolithos/neolua#30]
please consider the following code:

```c#
using Neo.IronLua;
using System;

namespace ztests {
    class Program {
        static void Main(string[] args) {
            Folder fd = new Folder { SomeId = 1 };
            File fl = new File { Folder = fd};

            using (Lua le = new Lua()) {
                Func<File, Boolean> f0 = le.CreateLambda<Func<File, Boolean>>("f0", "return fl.Folder.SomeId == 1", "fl");
                Console.WriteLine("f0: {0}", f0(fl));
                Func<File, Boolean> f1 = le.CreateLambda<Func<File, Boolean>>("f1", "return fl.Folder.SomeId == 0", "fl");
                Console.WriteLine("f1: {0}", f1(fl));
                Func<File, Boolean> f2 = le.CreateLambda<Func<File, Boolean>>("f2", "return fl.Folder.FakeId == 1", "fl");
                Console.WriteLine("f2: {0}", f2(fl));
            }
        }
    }

    public class Folder {
        public int SomeId { get; set; }
    }

    public class File {
        public Folder Folder { get; set; }
    }
}
```
it outputs:
> f0: True
> f1: False
> f2: False

which, from a certain point of view, is correct.

But `fl.Folder.FakeId` does not exist. Is it possible to have NeoLua raise an exception or any kind of flag in such case ?

**Comment by neolithos** [comment]
The third expression compares `nil` with `1`, which is false.

That unknown members do not raise an exception, is by design. Currently, I try to redesign the whole LuaType-system, so I will keep this in mind, and see what I can do.

After writing a lot NeoLua code it, might be a good idea, to raise a exception. Because, this is a real common mistake. I also hate the "Can not call nil." error ;-).

But I have no idea how other people will react on such a change,

**Comment by tschmit** [comment]
can't you just set a flag somewhere to warn about this? I'm looking for a way to warn an application user that the expression is not correct.

**Comment by neolithos** [comment]
The branch "LuaTable" address this issue. But it is not finished, yet.

**Comment by neolithos** [comment]
The commit 91181eee5702dfdd5c12233d2cfabbf4909b7aa4 should solve this problem.

Just write `:` instead of `.`.
```Lua
clr.System.Environment:UserName
```

There is also a beta-version on nuget.
