### ISSUE TITLE
find with multiple returns

### ISSUE THREAD

**Issue by tschmit** [neolithos/neolua#31]
string testst = "fsdfsdF/R/1/EP";
    string chunkbody = "function getOrig(z) _,_,o = string.find(z, '.*/.*/.*/(.*)'); return o; end;";
    using (Lua le = new Lua()) {
        dynamic g = le.CreateEnvironment();
        g.dochunk(chunkbody, "test.lua");
        Console.WriteLine((string)g.getOrig(testst));
    }

displays 
> fsdfsdF/R/1/EP

when according to http://www.lua.org/cgi-bin/demo, it should display
> EP

**Comment by neolithos** [comment]
Thanks for the hint.

Sorry, for the missing tests on the std libs, I still hope that someone will take care of them (define the necessary tests).

**Comment by tschmit** [comment]
ok, next time I'll try to write some tests and make a pull request.

thanks for all

**Comment by neolithos** [comment]
That would be nice.
