### ISSUE TITLE
Handling of require doesn't work if StandardPackagesPath is changed

### ISSUE THREAD

**Issue by fooo** [neolithos/neolua#32]
In _NeoLuaD / Lua.Libraries.cs_ there is a return from the loop as soon as _LuaRequireCheckFile_ is called. This means only the first path in paths is checked, so scripts in a path added to __StandardPackagesPath__ will never be found (see line 130 below).

```java
123 			foreach (string c in paths) 
124 			{ 
125 				if (String.IsNullOrEmpty(c)) 
126 					continue; 
127 				else 
128 				{ 
129 					sFileName = System.IO.Path.Combine(c, sModName + ".lua"); 
130 					return LuaRequireCheckFile(ref sFileName, ref dtStamp); 
131 				} 
132 			} 
```

**Comment by neolithos** [comment]
Thx.
