### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by alanprot** [neolithos/neolua#35]
Hello,

Are there any plans for the neolua to support the new .NET Core version? 

Tks

**Comment by neolithos** [comment]
Yes, that was the reason for splitting the lib in a Core and a Desktop part. If you only use the core part it will not be compatible to the C-Lua-runtime. You have to create your own environment.

The last test in November showed a bug in .net core, that should be fixed, now.
I did not test it, again. So, let me know, if it works.

**Comment by akatz0813** [comment]
Hi @neolithos any further thoughts on .NET Core support now that 1.0 is out?

**Comment by neolithos** [comment]
I have currently no opportunity to play around with .NET core :(.

The codebase should support .NET core, so feel free to try it out, and report me the issues or positive feedback. That would be a big help.
I hope there are no big problems.

**Comment by orthoxerox** [comment]
Okay, I tried migrating the projects to netstandard2.0 wherever possible and got the following errors in NeoLuaD:

```
Exceptions.cs(92,17): error CS0246: The type or namespace name 'Closure' could not be found (are you missing a using directive or an assembly eference?) [***\neolua\NeoLuaD\NeoLuaD.csproj]
LuaStackTraceDebugger.cs(393,41): error CS1061: 'AppDomain' does not contain a definition for 'DefineDynamicAssembly' and no extension method 'DefineDynamicAssembly' accepting a first argument of type 'AppDomain' could be found (are you missing a using directive or an assembly reference?) [***\neolua\NeoLuaD\NeoLuaD.csproj]
LuaStackTraceDebugger.cs(394,24): error CS1501: No overload for method 'DefineDynamicModule' takes 2 arguments [***\neolua\NeoLuaD\NeoLuaD.csproj]
LuaStackTraceDebugger.cs(408,10): error CS1061: 'LambdaExpression' does not contain a definition for 'CompileToMethod' and no extension method 'CompileToMethod' accepting a first argument of type 'LambdaExpression' could be found (are you missing a using directive or an assembly reference?) [***\neolua\NeoLuaD\NeoLuaD.csproj]
```

According to this SO question, it's a limitation of netstandard that wasn't removed even in 2.0: https://stackoverflow.com/questions/41520319/alternatives-of-compiletomethod-in-net-standard

It compiles fine via the new csproj format if I target the .net framework, though. Is it fine if I submit a PR when I'm done converting all the projects?

**Comment by neolithos** [comment]
Thanks, for investigating. This part is still on my agenda.

A PR would be nice. Or you can also commit the changes in your repo and leave a comment here.

**Comment by orthoxerox** [comment]
Could you check if this branch compiles and tests ok? https://github.com/orthoxerox/neolua/tree/dotnet-cli

I tried fixing all projects, but I cannot verify that all of them work, since I don't have Windows Phone or Win 8.1 SDK on the machine. I also don't have 4.5.1 SDK on this machine, so I upgraded desktop projects to 4.6.1 to test them. You can downgrade them to see if they work, netstandard1.2 is supposed to be compatible with 4.5.1.

**Comment by neolithos** [comment]
Looks good, thx.

Just remove this Project. It is not useful anymore.

It is also good, that you created a new branch, we should let this seperated during a beta phase. I will try compile a beta release for your work and see how it will work out.

**Comment by NotoriousRebel** [comment]
Any updates on this?

**Comment by neolithos** [comment]
I use the lib for .net core.

Current targets:
- net45
- net47
- netstandard2.0
- netcoreapp2.0
