### ISSUE TITLE
Can avoid return multiple values?

### ISSUE THREAD

**Issue by BennetWang** [neolithos/neolua#36]
I have a simple script(local ret;ret=request; return ret;).when I make the request argument a Array value,the script return multiple values.When I make  the request argument a List Value,the Script return a single value.How Can I make the return of the first case  as well as the second case?

**Comment by neolithos** [comment]
Which version do you use?
I changed this part, that only Results, where split in its single values.
May be a return (ret); will fix it in the short run.

```Lua
function arr() return clr.System.String[](1,2,3); end;
local a = arra();
return a; -- returns a array
```

```Lua
function arr2() return 1,2,3; end;

return arr2() -- 3 values

return (arr2()) -- 1 value

local a= arr2();
return a; -- 1 Value
```

**Comment by BennetWang** [comment]
But,If I make  the request argument a object array(request=new object[] {"a","b" }),I get two return values.

**Comment by neolithos** [comment]
I wrote folling example:
```C#
using (var l = new Lua())
{
  dynamic g = l.CreateEnvironment();
  var c = l.CompileChunk("local v = arg; return v;", "test", null, new KeyValuePair<string, Type>("arg", typeof(object)));
  var r = c.Run(g, 3);
  Console.WriteLine(r);
  r = c.Run(g, new int[] { 1, 2, 3 });
  Console.WriteLine(r);
}
```
It returns always one result:
```
{3}
{System.Int32[]}
```
with the current version.
