### ISSUE TITLE
Please updated the basic documentation

### ISSUE THREAD

**Issue by amarnathchatterjee** [neolithos/neolua#37]
Hi,
Please update the basic documentation otherwise its difficult to even get started. The below line from "Getting started" documentation doesn't works 

> using (LuaChunk chunk = l.CompileChunk(c, Lua.DefaultDebugEngine))

**Comment by amarnathchatterjee** [comment]
From the source code it seems, LuaChunk doesn't impletment IDisposable. Would this be the right alternative ?

> LuaChunk chunk = l.CompileChunk("xxxx", StrLuaLogic, LuaDeskop.StackTraceCompileOptions);

**Comment by neolithos** [comment]
Sry, I will fix this as soon as possible. Currently, I am on vacation :)

**Comment by neolithos** [comment]
Thx.
