### ISSUE TITLE
Using Constants

### ISSUE THREAD

**Issue by lucid2310** [neolithos/neolua#38]
What is the best approach to using constants declared in C# in the lua script.

FYI: When I try calling the EntityStates.RESTING without passing the reference it throws an exception.

C#: 
             `_inputs.Add("target", this);`
            ` _inputs.Add("constants", typeof(EntityStates));`

Lua Script:
             `local EntityStates = inputs["constants"];`
		
        `if (entity.StateManager.HasState(EntityStates.RESTING) == true) then
            hpRegen = (((entity.GetValue("level") + 20) *1) / 750);`

**Comment by neolithos** [comment]
Hi,
this shouldn't work with the current version.

But what will work for sure, wrap the type to the NeoLua type system. So, you will get access to all the static members.
```C#
_inputs.Add("constants", LuaType.GetType(typeof(EntityStates));
```
A good way to use the members is, to use the member operator:
```Lua
local EntityStates = inputs["constants"];
a = EntityStates:RESTING
```
This will throw an exception on typos.

Another way to use constants/types is:
```Lua
const EntityStates typeof Namespace1.EnitityStates;
a = EntityStates:RESTING
```

All clearified?

**Comment by lucid2310** [comment]
Thanks, I will test this out tonight! You are correct it does not work, I thought it did at first since the script was not crashing, but found out the constants being used in the script were just set to 0.
