### ISSUE TITLE
LuaAssert method should call LuaError

### ISSUE THREAD

**Issue by fgretief** [neolithos/neolua#4]
The LuaAssert method in LuaGlobal.cs uses the Debug.Assert function. This causes problems because that assert will terminate the application in Debug mode and do nothing in Release mode..

We use assert for unit testing and expect a LuaRuntimeException to be thrown with the message supplied to the assert function and check for it in the tests. A test suite can have many tests, each able to fail.

In Lua 5.2, the assert function calls the error function, so this behavior is consistent with how the language works. The patch below illustrate the suggested change.

```patch
--- a/NeoLua/LuaGlobal.cs
+++ b/NeoLua/LuaGlobal.cs
@@ -267,7 +267,8 @@ namespace Neo.IronLua
 		[LuaMember("assert")]
 		private static object LuaAssert(object value, string sMessage)
 		{
-			Debug.Assert(IsTrue(value), sMessage);
+			if (!IsTrue(value))
+				LuaError(sMessage ?? "assertion failed!", 1);
 			return value;
 		} // func LuaAssert
```

**Comment by neolithos** [comment]
There is nothing to add.
Thank you, I wiill change the function within the next day (when I am back at home).

**Comment by neolithos** [comment]
Do you need a release?
Because, this is the only change since the last one. And there is no preasure to push one.

**Comment by fgretief** [comment]
Thanks for the fix.
No need for a release. I am building from source at the moment.
