### ISSUE TITLE
Attempt to use wrong overload.

### ISSUE THREAD

**Issue by DanielElam** [neolithos/neolua#40]
I believe I've commented about this issue before, but I can't seem to find the original post.

I have two constructors: one takes 3 floats and the other takes 2 Vector3 objects.
When calling the constructor with 2 Vector3s, it tries to use the 3-float operator, resulting in a `No conversion defined from Vector3 to Single.` exception. I have trouble understanding why it would ever want/need to pick an overload that doesn't even have the same number of arguments.

I don't plan on using any BCL/clr code from Lua, and compatibility with existing scripts is more important in my project, so if this behaviour can't be fixed without affecting clr-compatibility, it would be nice to have it as a compile option.

This was tested with both 1.2.5 and the latest commit.

Example:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;
using Neo.IronLua;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            using (Lua l = new Lua())
            {
                var t = new LuaGlobalPortable(l);
                t.RegisterPackage("CFrame", typeof(CFrame));
                t.RegisterPackage("Vector3", typeof(Vector3));
                var c = l.CompileChunk(
                    @"
local v = Vector3(1, 2, 3)
local test1 = CFrame(v, v) -- no error

local test2 = CFrame(v, Vector3(1, 2, 3)) -- error

return test3
", "test", null);
                var r = c.Run(t);
            }
        }

        class Vector3
        {
            public float x;
            public float y;
            public float z;

            public Vector3(float x, float y, float z)
            {
                this.x = x;
                this.y = y;
                this.z = z;
            }
        }

        class CFrame
        {
            public float x;
            public float y;
            public float z;

            public CFrame(float x, float y, float z)
            {
                x = x;
                y = y;
                z = z;
            }

            public CFrame(Vector3 v0, Vector3 v1)
            {
                x = v0.x + v1.x;
                y = v0.y + v1.y;
                z = v0.z + v1.z;
            }
        }
    }
}
```

**Comment by neolithos** [comment]
In the thread #26 Jan 20 is the long explaination.

To fix this in you should also create a constructor like:
```C#
public CFrame(params object[] args)
{
}
```
or
```C#
public CFrame(object a, object b, object c)
{
}
```
or
```Lua
local test2 = CFrame(v, (Vector3(1, 2, 3))) -- hopefully no error
```

I plan to implement typed returns, but it is complicated. And over the summer I will have no time.

**Comment by ggDanDev** [comment]
I tried creating a dictionary of constructorInfos, where the key was the number of arguments and invoked it based on the length of params object[], but the performance was abysmal. (0.3ms more at 100000 iterations)


>So, the type system try to find an overload, that looks like
>Call: Neo.IronLua.LuaResult, Neo.IronLua.LuaResult
>Defined are two overloads (with the score):

>Reset member: Void .ctor(Single, Single, Single)
>      Result: OnBegin=0, Exact=0, Implicit=0, Explicit=2147483647, ParameterLength=3
>Reset member: Void .ctor(ExtTest.Vector3, ExtTest.Vector3)
 >     Result: OnBegin=0, Exact=0, Implicit=0, Explicit=2147483647, ParameterLength=2 

>The first one, gets the highest score, because of the parameter length:

Why does it get the highest score because of the parameter length, if 3 != 2?
I don't have any overloads that share the same ParameterLength; does that not mean it can just ignore types?

**Comment by neolithos** [comment]
It does'nt know the exact length of the given arguements, it things that you give 2147483647 arguements (because of the undefined return value). So, 3 is better than 2.

That is the reason for the fix  `CFrame(v, (Vector3(1, 2, 3)))`. Because the length is two, now.

The loose of performance is a problem with dynamic languages. That is the reason, why NeoLua/DLR try to guess the static expression as often as possible (also during runtime). The infinite number of return values is hard to guess.

Btw. what also might work:
```Lua
local function Vector3(x : float, y : float, z : float) : Vector3
  return Namespace.Vector3(x, y, z);
end;
```

**Comment by ggDanDev** [comment]
> Lua doesn't know the exact length of the given arguements

But doesn't ``TARG[] arguments`` have the exact (beside tuples) length?

**Comment by neolithos** [comment]
But the length is not static, that is the reason, why the algorithm chooses the longes member. Because the array could be 2 or 3 (or any other number).
