### ISSUE TITLE
Adding methods to existing libraries not working.

### ISSUE THREAD

**Issue by tvandijck** [neolithos/neolua#46]
Additional information: 'LuaLibraryString:capitalized' not found.

a script with this in it:

``` lua
    function string.capitalized(self)
        return self:gsub("^%l", string.upper)
    end
```

**Comment by neolithos** [comment]
You want to call:
```Lua
return string.capitalized("hello");
```
and not
```Lua
return "hello":capitalized();
```
This fails on https://www.lua.org/cgi-bin/demo.


At the moment the LuaLibraries are designed as a set of static classes, with no way to expand them.
c-Lua uses a table for this class.

I will try to find a solution.

**Comment by tvandijck** [comment]
```lua
function string.capitalized(self)
   return self:gsub("^%l", string.upper)
end

local s = "hello"
print(s:capitalized())
```

works fine on that demo page, that is actually a cool little page... never know that existed...
but yeah, as you mentioned the problem is due to the LuaLibraries being a static class. Which is a bummer, because we use that alot, and while we can certainly look at porting that lua code to C#, we got quite a lot of scripts we don't control ourselves that do stuff like this too...

it would be awesome if you could find a solution for sure...

**Comment by neolithos** [comment]
To create a string library that is expandable is pretty easy.
First way: Just create a table in your lua code and copy the function pointer from the static class to this new table. Nice work a round.

Secound: I'am currently thinking about a rewrite of the library stuff, and I will make it possible to extend them .

But:
I have no good solution for the `s:capitalized()`-call:
Register a method __newindex (or override OnNewIndex) and call  RegisterMethodExtension. 
Two Problems:
- There is no protection for reregistering the same method (easy solvable)
- LuaType is a single instance construct and do not know anything about the lua environment (`_G`). Every change to the type system is global. That could be a advantage, if you design the library also as a single instance member. You could have the same environment with different runspaces.


I will play with the semver-Script a little soon.
