### ISSUE TITLE
Get chunk name from method?

### ISSUE THREAD

**Issue by DanDevPC** [neolithos/neolua#48]
I have an event system where scripts can add functions as listeners. I want to disconnect the listener if a flag in the script is set, but I don't know how to access the script/chunk name from the MethodInfo.

**Comment by neolithos** [comment]
The hard way to do this, but the most flexible, is to implement your own Debug-Interface:
https://github.com/neolithos/neolua/blob/master/NeoLua/LuaDebug.cs

You need to implement `ILuaDebug`. In your first test you should return for `Level` `None` and override `CreateChunk`.

You need the return a LuaChunk, that holds all your information, that you will need in later use.

**Comment by DanDevPC** [comment]
Does `CreateChunk` get called for every function or just for the entire script? Because right now I'm setting the script's chunk name to a GUID which I can lookup in a dictionary to get the script. But I don't have access to the chunk name from a random function delegate.

**Comment by neolithos** [comment]
It is called for every chunk. You have the map the `(LambdaExpression)expr` argument.

You might create a sub dictionary for the sub functions. It also possible to wrap expressions the get the Delegate. The best way to do this, is to implement a expression visitor.

An example is:
https://github.com/neolithos/neolua/blob/master/NeoLuaD/LuaStackTraceDebugger.cs

**Comment by DanDevPC** [comment]
So I would need to add an entry to a dictionary for each `VisitLambda`? Would I be able to use both a custom `ILuaDebug` and the `TraceLineDebugger` at the same time?

**Comment by neolithos** [comment]
At first I need to make the chunk generation overridable. After this, there will be no problem.
