### ISSUE TITLE
Reload script at runtime

### ISSUE THREAD

**Issue by thoj** [neolithos/neolua#49]
Hi

I'm writing a scripting engine for an internal tool. One thing I would like to implement is on the fly reloading when the script file changes on disk. The tool is long running and calls a member function loaded from a Lua script continuously. I need to be able to reload this script while the tool is still running. This is what i have tried:

Please excuse the Pesudo-code
```c#
if (scripts_changed) {
                try
                {                    
                    lua = new Lua();
                    chunk = lua.CompileChunk(script_file, new LuaCompileOptions() { DebugEngine = LuaStackTraceDebugger.Default });
                }
                catch (LuaParseException e)
                {
//... Parse error. just return and try again.
                }
                try
                {
                    global = lua.CreateEnvironment<LuaGlobal>();
                    global.DoChunk(chunk);
                }
                catch (Exception e)
                {
// ... just return and try again
                }
}

try
{
   global.CallMember("Something"); //This fails after fixed runtime error.
}
catch (Exception e)
{
//... oof
}
```

The script_changed is just set when a *.lua file changes via FileSystemWatcher and when starting up. 

1. Start up. Script runs OK.
2. Introduce change. Script runs OK
3. Introduce parse error. Fails with parse exception.
4. Fix Parse error. Script runs OK.
5. Introduce runtime error. Script Fails with runtime exception. 
6. Fix runtime error. Script fails with cant find member function exception. 

Only way to fix this is to restart the whole program. I've tried lua.Clear(),global.Clear(),lua = null, global = null and creating new instances. But it seems the program keeps old script data around and can't be cleared and still fails on reload even if the error is fixed. 

I'm probably missing something fundamental here. And tips on how to do this properly? 

I'm Using v1.2.8. But i could find any relevant commits that my have fixed this.

Thanks for you help :)

Here are the exceptions i'm getting in the runtime error case:
** Runtime Error Introduced **
Script changed... Reloading.
Exception: Can not call nil value.
Exception:  -- internal --
 at [L] main8(LuaTable _G) line main.lua:22:1

Runtime Error: Value cannot be null.
Parameter name: 'table:Scan' not found.
Runtime Error:  at [C] Neo.IronLua.LuaTable.CallMemberDirect(String memberName,Object[] args,Boolean ignoreCase,Boolean rawGet,Boolean throwExceptions) line C:\Projects\NeoLua\NeoLua\LuaTable.cs:2824:8
 at [C] Neo.IronLua.LuaTable.CallMember(String memberName) line C:\Projects\NeoLua\NeoLua\LuaTable.cs:2771:7
 at [C] MyProgram.LuaScript.ScriptTask() line c:\bla\bla.cs

** Runtime Error Fixed **
Script changed... Reloading.
Runtime Error: Failed to call 'Scan'.
Runtime Error:  at [C] Neo.IronLua.LuaTable.CallMemberDirect(String memberName,Object[] args,Boolean ignoreCase,Boolean rawGet,Boolean throwExceptions) line C:\Projects\NeoLua\NeoLua\LuaTable.cs:2869:6
 at [C] Neo.IronLua.LuaTable.CallMember(String memberName) line C:\Projects\NeoLua\NeoLua\LuaTable.cs:2771:7
 at [C] MyProgram.LuaScript.ScriptTask() line c:\bla\bla.cs

**Comment by neolithos** [comment]
Hi,

Do you have a small example application?
Do you have the same result with `Lua.RtInvoke`?

**Comment by thoj** [comment]
Well now I'm really embarrassed. I actually got it working fine a few hours after submitting this issue. I thought I fixed it by using a local LuaChunk variable and using a dynamic global instead of a fixed type. But now I can't recreate the bug. 

Here is a minimal test program that is very close to what I'm doing:

https://gist.github.com/thoj/904c46efa960a06e038ff86de0dcdb81

Notice that I need to persist a object when reloading. I thought maybe this was the issue but now it works fine. At first glance I think there might be a memory leak but I'm not sure. You can check out the code above and tell me if I'm doing anything stupid. But I think you can close this issue as I can't recreate it. I'll reopen if i encounter it again. Sorry about the noise.

**Comment by neolithos** [comment]
Interesting. But it seems there is something wrong in the caching.
But, I do not get it reproduced.

Do you have the innerException for "Failed to call 'Scan'."?

btw.
What can be dangerous at your code: You create always a new environment and engine? Why?
In my opinion you only need one Lua engine and one global.

**Comment by thoj** [comment]
Annoyingly I can't crecreate the error either. It must have been something wirld in one of my scripts. I use dofile to load more scripts from the main script. I trtied going back to an older commit. But it still works 🎱 


I use a new script engine / enviorment to avoid memory leaks. But not sure if that is the right way. Using the same script engine / enviroment seems to leak memory:

https://gist.github.com/thoj/52057dd7331ab776e3ce63e0950856b1

**Comment by neolithos** [comment]
It should only seems. Because the engine builds a cache of the different call paths.

Schade. I had hidden errors.

FYI:
I use two LuaTable's for such scenarios. One for the chunk initialisation and one for the runtime variables. But this needs a little bit more work.

**Comment by neolithos** [comment]
My thoughts are composed in the commit 987f0927b0dafaf5f4380ad639832beb82a7b2be.

Is this helpful?

**Comment by PatrickKursawe** [comment]
Extremely. Thanks alot!
