### ISSUE TITLE
About table.sort with function

### ISSUE THREAD

**Issue by xiaomiaozone** [neolithos/neolua#53]
When I sort a table like this:
```lua
	local tbl = {{1,2}, {2,3}, {2,0}}

	table.sort(tbl , function(a , b)
			return false
		end)
```
In NeoLua 5.3 (1.2.21.0) it told me "INNER EXCEPTION", but in Lua 5.3 it can be use.

**Comment by neolithos** [comment]
Thx, for reporting.
Is this fix correct?

**Comment by xiaomiaozone** [comment]
Yes, it can be used well. :)
