### ISSUE TITLE
Redirect stdin/stdout

### ISSUE THREAD

**Issue by xionglingfeng** [neolithos/neolua#54]
How to redirect stdin/stdout/stderr when using NeoLua in C#?

**Comment by neolithos** [comment]
What exactly do you mean with redirect?

**Comment by xionglingfeng** [comment]
For example, control where the output goes for `print()` function runs in Lua.

In IronPython, it can be done through calling the `ScriptEngine.Runtime.IO.SetOutput(stream, encoding)`, `ScriptEngine.Runtime.IO.SetInput(stream, encoding)` and `ScriptEngine.Runtime.IO.SetErrorOutput(stream, encoding)`

Similar as Moonsharp, redirecting can be done by setting `Script.Options.Stdin = stream`, `Script.Options.Stdout = stream` and `Script.Options.Stderr = stream`.

**Comment by neolithos** [comment]
The **io** package has two default streams, they are initialized with null by default.
The **print** function does not use the io package. You can create your own environment, just override the current implementation (inherit from `LuaGlobalDesktop`).

I did no make the constructor of `LuaFile` public, so you have to inherit a new class, that will initialize the streams as you want.

Now, your own implementation of the environment, can set the default streams from **io** via `io.output`, `io.input` with an instance of you `LuaFile`-class.

I know, that is not very user friendly. But if you have a good idea, for a god way, how it should be done. Let me know.

**Comment by neolithos** [comment]
Hi,
did what I decriped in the post above. This should help you.

Thx, for testing.
