### ISSUE TITLE
About "break"

### ISSUE THREAD

**Issue by xiaomiaozone** [neolithos/neolua#55]
I found two problems when I use it.
```lua
repeat
	break
	if true then end
until true
```
In NeoLua 5.3 (1.2.21.0) it told me "Unexpected token 'if'. 'until' expected.", In Lua 5.3 it can be use well.

And another:
```lua
local l = {}
l[1] = {v = 26}
l[2] = {v = 20}
table.sort(l, function(a, b) return a.v < b.v end)

print(l[1].v)
print(l[2].v)
```

In lua 5.3 is:
```
20
26
```
But NeoLua no sort them.

**Comment by neolithos** [comment]
Thx, for finding the issues.
If you need a release let me know.
