### ISSUE TITLE
How to call .NET-async method in Lua-script with awaiting?

### ISSUE THREAD

**Issue by posledam** [neolithos/neolua#58]
Tell me please, is this possible?

**Comment by neolithos** [comment]
Yes, it is possible. The easiest way is to call the Wait method, like
```Lua
MethodAsync().Wait();
```
But this can cause deadlock situations, so you need a little helper. That checks first, if you a in the UI-Thread-Context:
Example for WPF:
```C#
if (SynchronizationContext.Current is DispatcherSynchronizationContext)
{
  var frame = new DispatcherFrame();
  t.GetAwaiter().OnCompleted(() => frame.Continue = false);
  Dispatcher.PushFrame(frame);
}
return t.Result;
```

Btw. It is not possible to write a async method.

**Comment by hVostt** [comment]
`Wait()` looks like a synchronous call with a wait in the current thread. Of course, I meant the asynchronous call, maybe a coroutine? Or use some Lua function as continuation?

Thank you.
