### ISSUE TITLE
can this support mult threads?

### ISSUE THREAD

**Issue by FashGek** [neolithos/neolua#60]
NeoLua Version:
my server has many threads, the manager will scheluder those threads, some times task A will call the lua function, some times schedule task B call functions.
is this possible.
Example to reproduce:
```Lua
```

**Comment by neolithos** [comment]
Yes it is, with under the same rules .net code has.

**Comment by SystemKeeper** [comment]
@neolithos Sorry for bumping this, but can you please have a look here? Thanks!

**Comment by neolithos** [comment]
@SystemKeeper sry, i did not get any notification.

1. Yes, it is possible. The binder cache should be thread safe, only the call cache has no monitor. Currently, I do not noticed any problems. The call-cache should repair it self.
2. You can, but you should secure you variables with a monitor. LuaTable is also **not** thread safe, but you can also secure it with a monitor. I normally use some helper, developed in c#.
If you only read, you do not need any thread safe stuff.
3. It depends. For performance it is better to have only one.

NeoLua is really near to the .net framework. So, it follows the same rules. For more hints and tipps I need more information.

All clear.
