### ISSUE TITLE
How could I compile from source code by vs2017. it report ALINK : error AL1078:

### ISSUE THREAD

**Issue by FashGek** [neolithos/neolua#61]
NeoLua Version:

Example to reproduce:
```Lua
```

**Comment by FashGek** [comment]
change the property of project NeoLua(Portable) to netframe 4.6

**Comment by neolithos** [comment]
You have no .net core installation?

**Comment by FashGek** [comment]
so you mean I can build it from source code by dotnet core with vscode

**Comment by FashGek** [comment]
when I get the neolua dll with vscode nuget. it said the target framwork is net4.5, so i suppose you donot supoort dotnet core

**Comment by neolithos** [comment]
I use Visual Studio 2017 Prof, I never tried vscode, but in the end all is running through a msbuild script.
