### ISSUE TITLE
How could send params when do chunk?

### ISSUE THREAD

**Issue by FashGek** [neolithos/neolua#65]
var brooder = _context.Queen.Optstr("brooder", @"brooder.lua");
var chundk = _l.CompileChunk(brooder, LuaDeskop.StackTraceCompileOptions, new KeyValuePair<string, Type>("a", typeof(string))); //_l.CompileChunk(brooder);
var args = new List<object>();
args.Add(msg);
_g.DoChunk(chundk, args.ToArray());

---below is lua file content
print(...)
--
this code cause expection. as below picture
![qq 20180322181752](https://user-images.githubusercontent.com/2861035/37764827-978149e2-2dfd-11e8-8e62-83906090a38d.png)

**Comment by neolithos** [comment]
You defined only one argument for this chunk "a".
There is no vararg definition. Vararg's are only allowed with Lua-functions.

**Comment by FashGek** [comment]
you mean i canno define a vararg argumen when call do chunk

**Comment by neolithos** [comment]
Correct. As I know this is also not allowed in c-lua.
