### ISSUE TITLE
maybe it is a bug in string.gsub

### ISSUE THREAD

**Issue by FashGek** [neolithos/neolua#66]
print(string.gsub('192.128.33.15', '[0-9]+', 'x'))
print(string.gsub('192.1#8.33.15', "#", 'x'))
those code above work fine. but the code below cannot work , and the enteresting things is it will block the lua means it dose not resume, also say something wrong
   zlog(string.gsub('192.1?8.33.15', "?", 'x'))

**Comment by FashGek** [comment]
it seams like it dose accept ? as the pattern,

**Comment by neolithos** [comment]
Do you have the stacktrace of the deadlock situations?
