### ISSUE TITLE
lua function require is nil?

### ISSUE THREAD

**Issue by FashGek** [neolithos/neolua#67]
require("book") throw a exception "Can not call nil value."

**Comment by FashGek** [comment]
I know my problem. when create a environment should give it a argemtn LuaGlobal as below
 _g = _l.CreateEnvironment<LuaGlobal>();

**Comment by RussellHaley** [comment]
Markdown removed the important part of the solution because it removed everything between the chevrons. The above should read: 

_lua = _luaMain.CreateEnvironment&lt;LuaGlobal&gt;();

**Comment by neolithos** [comment]
This will be changed in 1.3.x.0.
Because, I compile 4 different libraries, with a platform specific version of LuaGlobal.

Hint: I always inherit from LuaGlobal in my projects and add my stuff to.
