### ISSUE TITLE
require function throw exception?

### ISSUE THREAD

**Issue by FashGek** [neolithos/neolua#68]
NeoLua Version:

a.lua

local b = require "b"

b.foo()

b.lua

local b = {}

function b.foo() 
end

return b

-------
the code above throw exception.in LuaTable.cs BindConvert
public override DynamicMetaObject BindConvert(ConvertBinder binder)

System.ArgumentException: 'type “System.String” no default constructor.'

**Comment by FashGek** [comment]
![default](https://user-images.githubusercontent.com/2861035/37871064-240545a6-3017-11e8-8196-5cfda36b5019.PNG)
this is the picture

**Comment by neolithos** [comment]
Is this solved, and how?
