### ISSUE TITLE
delegate with arguments signature will throw exception

### ISSUE THREAD

**Issue by FashGek** [neolithos/neolua#69]
NeoLua Version:
C#
namespace main{
public delegate void Hook(int type);

class program
{
   static void Main()
   {
   }
}

class XXLua
{
        public XXLua()
        {
            var s = XXLua.GetLines("Lua.Coroutines01.lua");

            var g = l.CreateEnvironment<LuaGlobal>();
            g["hook"] = new Action<int, Hook>(hook);
            g["counter"] = n;

            g.DoChunk(s, "test.lua");
        }
}
}

-----
lua

hook(2, function(v):void
	
end)

----the code above will throw exception
![default](https://user-images.githubusercontent.com/2861035/37872367-c19f2e3c-3038-11e8-8bd3-035a85044694.PNG)

: Cannot bind to the target method because its signature or security transparency is incompatible with the signature or security transparency of the delegate type.

**Comment by neolithos** [comment]
```Lua
hook(2, function (v : int) : void end)
```
Should be correct.

**Comment by FashGek** [comment]
that worked
