### ISSUE TITLE
LuaType.LookupReferencedAssemblies setter always sets the member to true

### ISSUE THREAD

**Issue by Phosphan** [neolithos/neolua#7]
A problem with the setter: You set the variable to "true" instead of "value". 
The bad thing is also that this value is already used by the static constructor, so you can't change it before it is used for the first time.
My application has 170+ assemblies loaded, and initializing Lua takes more than 20 seconds. Looks like the type resolution machanism could be a bit optimized... trying to work around this with a seperate application domain for now.

**Comment by neolithos** [comment]
Problem fixed.

170+ assemblies. This is a lot. Do you know, were exactly the 20sec are gone?

**Comment by Phosphan** [comment]
Just iterating through the lists while comparing the names eats most of the
time, it seems. 170 times + references scanning through a list of 170
entries...  does not scale well.

Thanks for the quick response - will try the fix maybe on wednesday.

-Patrick

neolithos <notifications@github.com> schrieb am Mo., 23. Mär. 2015 20:00:

Problem fixed.

**Comment by neolithos** [comment]
The start up of LuaType or Lua is small (I thing).
I need a hint where I have to look at?

**Comment by Phosphan** [comment]
Stack trace to the first Resolve-call follows.
It is trying to resolve the "type" "System" in this first call.

When I host the Lua object in a different AppDomain, the call to Lua.CreateEnvironment takes about 250 ms.
ResolveType is hit 8 times and takes a total of 200 ms.
About 130 ms go to the If-clause in the "collect references" block, 70 to the ReflectionOnlyLoad.
If I don't use the extra domain, the if clause eats most of the time - it is hit 478000 times. This is what takes so long - and it all happens before I even have the chance to ask for some type that might profit of the referenced assembly lookup.

When you start this lookup only after the LuaType class constructor, you get this down to barely noticable. I'll try to create my first pull request later :-)



 	Neo.Lua.dll!Neo.IronLua.LuaType.ResolveType() Zeile 438	C#
 	Neo.Lua.dll!Neo.IronLua.LuaType.Type.get() Zeile 712 + 0x8 Bytes	C#
 	Neo.Lua.dll!Neo.IronLua.LuaType.AddType(Neo.IronLua.LuaType type) Zeile 783 + 0xa Bytes	C#
 	Neo.Lua.dll!Neo.IronLua.LuaType.GetIndex(string sName, bool lIgnoreCase, System.Func<System.Type> buildType) Zeile 602 + 0x2c Bytes	C#
>	Neo.Lua.dll!Neo.IronLua.LuaType.GetType(Neo.IronLua.LuaType current, int iOffset, string sFullName, bool lIgnoreCase, System.Type type) Zeile 860 + 0x121 Bytes	C#
 	Neo.Lua.dll!Neo.IronLua.LuaType.GetType(System.Type type) Zeile 881 + 0x15 Bytes	C#
 	Neo.Lua.dll!Neo.IronLua.LuaType.RegisterTypeAlias(string sAlias, System.Type type) Zeile 933 + 0x8 Bytes	C#
 	Neo.Lua.dll!Neo.IronLua.LuaType.LuaType() Zeile 732 + 0x2e Bytes	C#
 	[Übergang von Systemeigen zu Verwaltet]	
 	[Übergang von Verwaltet zu Systemeigen]	
 	Neo.Lua.dll!Neo.IronLua.LuaGlobal.LuaLibraryTable.get() Zeile 839 + 0x23 Bytes	C#
 	[Übergang von Systemeigen zu Verwaltet]	
 	Neo.Lua.dll!Neo.IronLua.LuaTable.LuaTablePropertyDefine.GetPropertyStaticValue(Neo.IronLua.LuaTable t) Zeile 788 + 0x18 Bytes	C#
 	Neo.Lua.dll!Neo.IronLua.LuaTable.LuaTablePropertyDefine.GetInitialValue(Neo.IronLua.LuaTable table) Zeile 778 + 0x4b Bytes	C#
 	Neo.Lua.dll!Neo.IronLua.LuaTable.InitDefinition(int iIndex, Neo.IronLua.LuaTable.LuaTableDefine define) Zeile 1441 + 0x2b Bytes	C#
 	Neo.Lua.dll!Neo.IronLua.LuaTable.InitClass() Zeile 1427 + 0x2d Bytes	C#
 	Neo.Lua.dll!Neo.IronLua.LuaTable.LuaTable() Zeile 1376 + 0x8 Bytes	C#
 	Neo.Lua.dll!Neo.IronLua.LuaGlobal.LuaGlobal(Neo.IronLua.Lua lua) Zeile 137 + 0x8 Bytes	C#
 	Neo.Lua.dll!Neo.IronLua.Lua.CreateEnvironment() Zeile 347 + 0x18 Bytes	C#

**Comment by neolithos** [comment]
I see the problem. Setting the value let the process start :).

ResolveType looks a little imperformant. Do you use the library from source?
Your project might be a good one to speed this a little bit up.

At first, the best is to change the value of lLookupReferencedAssemblies to false during start up 1adac814325b38d733403408d32bd9110353383a.

Why I do this:
The lookup is needed because I have no assembly part on the type. I can just write Namespace.Namespace.Class. The C# compiler e.g. writes Namespace.Namespace.Class, Assembly.

Currently, I have no Idea how the change the algorithm?

**Comment by Phosphan** [comment]
Am 26.03.2015 um 16:01 schrieb neolithos:
>
> I see the problem. Setting the value let the process start :).
>
> ResolveType looks a little imperformant. Do you use the library from 
> source?
> Your project might be a good one to speed this a little bit up.
>
> At first, the best is to change the value of 
> lLookupReferencedAssemblies to false during start up 1adac81 
> <https://github.com/neolithos/neolua/commit/1adac814325b38d733403408d32bd9110353383a>.
>
> Why I do this:
> The lookup is needed because I have no assembly part on the type. I 
> can just write Namespace.Namespace.Class. The C# compiler e.g. writes 
> Namespace.Namespace.Class, Assembly.
>
> Currently, I have no Idea how the change the algorithm?
>
>
Well, caching already loaded assemblies would be a start. As well as 
trying to load the type for each loaded assemby before loading more 
assemblies. As well as arranging assemblies where you already found some 
time further up front in the list.
I think first checking the already loaded assemblies completely before 
starting to check the references could also help.

Just some suggestions...

Patrick

**Comment by neolithos** [comment]
Can you check out the performance of the new resolver?

**Comment by Phosphan** [comment]
Am 27.03.2015 um 01:55 schrieb neolithos:
>
> Can you check out the performance of the new resolver?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/neolithos/neolua/issues/7#issuecomment-86776094>.
>
Impressive. From 10 s per call down to 700 ms.

Thank you!

Patrick

**Comment by Phosphan** [comment]
I think we can call this closed.

**Comment by neolithos** [comment]
Nice to hear.

I hope, I did not mess something up.

Thank for the help.
