### ISSUE TITLE
lua table bug when the key is a thread

### ISSUE THREAD

**Issue by FashGek** [neolithos/neolua#70]
luacode
local p = {}
co = coroutien.create(function() end)
p[co] = 2

---after
p[co] = nil

then it trigger a exception

in luatable.cs funtion setvalue, when the key is a thread and the value is null , the ;SetValue function go into
// something else if branch
it calcualte the key index, which key is a thread, by the bit ofperation 
var hashcode = key.gethashcode() & 0x7FFFFFF;
so the hashcode value less than 0,
then trigger the outside the index exception

**Comment by neolithos** [comment]
```Lua
local p = {}
co = coroutine.create(function() end)
p[co] = 2
p[co] = nil
return p,co
```
returns:
```
  [0] = (table)table
  [1] = (thread)Neo.IronLua.LuaThread
```

**Comment by FashGek** [comment]
this is the picture
![default](https://user-images.githubusercontent.com/2861035/38476469-7cd20546-3be0-11e8-9e53-fd0275b6c63c.PNG)

**Comment by FashGek** [comment]
but my application is very complex. the code remove a item in a table within a coroutine

**Comment by FashGek** [comment]
I tested as below
local function thread(f) 
    return coroutine.create(function(...) 
        f(...)
    end)
end

local pool = {}

local co1 = thread(function() 
    print("co1 1")
    local a = coroutine.yield("^co1 1")
    print("^co1 2", a)
end)

pool[co1] = 23
pool[23] = co1

print(coroutine.status(pool[23]))
print(coroutine.resume(pool[23], 23))
pool[co1] = nil
print(pool[co1])
print(pool[23])

this  work fine without thread

**Comment by FashGek** [comment]
yes, if we run a thread, and then operat the table in that thread, then the exception throw, code below
---
local zerg = require "zerg"

zerg.async_run(function() 

	local function thread(f) 
		return coroutine.create(function(...) 
			f(...)
		end)
	end

	local pool = {}

	local co1 = thread(function() 
		print("co1 1")
		local a = coroutine.yield("^co1 1")
		print("^co1 2", a)
	end)

	pool[co1] = 23
	pool[23] = co1

	print(coroutine.status(pool[23]))
	print(coroutine.resume(pool[23], 23))
	pool[co1] = nil
	print(pool[co1])
	print(pool[23])

end)
--
the zerg is the framwork i work on, not matter, the zerg.async_run can be treat as a thread, in that thread we do table remove item, then the exception occured

**Comment by neolithos** [comment]
The access to the table it self is not thread safe, only the language.

You need to build a 'Monitor/lock' around the setter and getter.

**Comment by FashGek** [comment]
you mean modiy the neolua

**Comment by FashGek** [comment]
can you fingure out the code which part of the source code

**Comment by FashGek** [comment]
private int FindKey(object key, int hashCode, IEqualityComparer comparer)
		{
#if DEBUG
			//if (key == null)
			//	throw new ArgumentNullException(Properties.Resources.rsTableKeyNotNullable);
#endif
			var hashLength = hashLists.Length;
			if (hashLength == 0)
				return -1;

			var hashIndex = hashCode % hashLength;
			Console.WriteLine("Find Index {0} {1} {2} {3}", hashCode, hashLength, hashIndex, ~hashIndex);
			var lastIndex = -1;
			if (comparer == compareStringIgnoreCase)
			{
				for (var i = hashLists[hashIndex]; i >= 0; i = entries[i].nextHash)
				{
					if (entries[i].hashCode == hashCode && comparer.Equals(entries[i].key, key))
						lastIndex = i;
				}
				if (lastIndex >= 0)
					return lastIndex;
			}
			else
			{
				for (var i = hashLists[hashIndex]; i >= 0; i = entries[i].nextHash)
				{
					if (entries[i].hashCode == hashCode && comparer.Equals(entries[i].key, key))
						return i;
				}
			}
			return ~hashIndex;
		} // func FindKey

---
why return ~hashindex. this cause the index less than zero

**Comment by FashGek** [comment]
the bug is not about thread, is about when delete item in a table, but the index is not in the hash list , so it return ~hashcode, 

-----------

    local pool = {}



	local function thread(f) 
		return coroutine.create(function(...) 
			f(...)
		end)
    end

    local m = thread(function() end)
    pool[m] = nil

--
the code above also throw out the exception

**Comment by neolithos** [comment]
Way one:
You need to write a small lua helper that synchronize your pool.
```Lua
do(t = Lock(pool))
  pool[m] = nil;
end;
```
^^ That is what I do.

Or you can also try to create a thread-safe LuaTable, by overriding OnIndex and OnNewIndex.

Hope that helps.
