### ISSUE TITLE
clr type as lua funtion argument error

### ISSUE THREAD

**Issue by FashGek** [neolithos/neolua#71]
NeoLua Version:

print(clr.System.Text.StringBuilder)

function _lh(a:clr.System.Text.StringBuilder):void
end

cannot use the clr type as funtion argument type, what is the right way.

Example to reproduce:
```Lua
```

**Comment by neolithos** [comment]
Without clr.
```Lua
function _lh(a : System.Text.StringBuilder) : void
end;
```
