### ISSUE TITLE
StackOverflowException with large input file.

### ISSUE THREAD

**Issue by hglee** [neolithos/neolua#73]
NeoLua Version: NeoLua Interactive Command NeoLua 5.3 (1.2.24.0) by neolithos

Example to reproduce:
```
:load load_fail.lua
```

[Samples.zip](https://github.com/neolithos/neolua/files/1969678/Samples.zip)

When I try to load large input file that autogenerated (about 730kib), I got StackOverflowException.

Is there some limit for file size?

**Comment by neolithos** [comment]
In the debug version all is working find.
It looks that the System.Reflection.Emit.DynamicMethod has a problem in the release version, it could be a problem in the DLR.

**Comment by hglee** [comment]
I have another clue for that.

- Release 32-bit Process(Any CPU with 'Prefer 32-bit'): Load success in 3339 ms
- Release 32-bit Process(x86): Load success in 3253 ms
- Release 64-bit Process(Any CPU): **StackOverflow Exception**
- Release 64-bit Process(x64): Load success in 2557 ms

**Comment by neolithos** [comment]
Confirmed.

The problem might be in DynamicMethod implemention. But the development environment also crashes, so I have no glue what is going wrong :-(

**Comment by neolithos** [comment]
As a work around you should have a look at [ToLson](https://github.com/neolithos/neolua/blob/ab87e224a09a2d63063087600c8e0e0e32f7f073/doc/04_04_table.md#serializedeserialize-to-a-lua-script-object-notation-lson).
