### ISSUE TITLE
Timezone bug

### ISSUE THREAD

**Issue by kpdenis** [neolithos/neolua#75]
NeoLua Version: 1.2.25

There is a problem with timezone, code 
_print("local: " .. os.date('%Y-%m-%d-%H:%M:%S', os.time()))_
prints invalid time.

Probably because timezone added twice.

https://github.com/neolithos/neolua/blob/master/NeoLuaD/Lua.Libraries.cs

method _LuaResult time(LuaTable table)_ 

line 244: _ts = DateTime.Now.Subtract(dtUnixStartTime);  //DateTime.UtcNow.Subtract(unixStartTime);_
So time returns in local timezone

line 258: _return new LuaResult(Convert.ToInt64(ts.TotalSeconds));_
returns as Int64

method _object date(string format, object time)_ interprets Int64 time as UTC
line 207: _dt = dtUnixStartTime.AddSeconds((long)Convert.ChangeType(time, typeof(long))).ToLocalTime();_

As result timezone added twice.

Example to reproduce:
```Lua
print("local: " .. os.date('%Y-%m-%d-%H:%M:%S', os.time()))
```

**Comment by neolithos** [comment]
I change it:
https://github.com/neolithos/neolua/blob/c1a089baa80de4c8ffbd39a2ea22ec31e5db438d/NeoLuaD/Lua.Libraries.cs#L203

Is the result correct, now?

Thx, for reporting.

**Comment by kpdenis** [comment]
Yes, it is.

Thanks!
