### ISSUE TITLE
Calling require() causes "Neo.IronLua.LuaRuntimeException: 'Can not call nil value.'" exception.

### ISSUE THREAD

**Issue by RussellHaley** [neolithos/neolua#78]
Hello! First off: brilliant library. I've been fighting on and off with trying to get Lua running in C# for some time now. This is SO much easier!!!

The first problem I have run into is that a print statement in Lua does not output anything to my debug console. Not sure about that, but it's not important (other than for debugging).

My main issue is that I can't seem to require a file. I've tried a number of different variations, but to no avail. The code posted runs with lua53 on the command line. I noted there is an issue #67 but I don't understand the solution that was posted. Details below. 

NeoLua Version: 1.2.25 (from Nuget)

**Example to reproduce:**
**hello.lua**
```Lua
--~ package.path = "Lua\\?.lua;"..package.path
local test = require 'Lua.testing'

local t = {one=1, two=2, [3]=0x03, four="four"}
local result = 0
for i,v in pairs(t) do

	if type(v) == 'number' then
		result = result + v
	end
end

print('value is:' .. result)


print(test.testing())

if result > 0 then 
	return result 
else
	return "Not what I expected"
end

```

**testing.lua**
``` Lua
local function testing()
	return "This is a test"
end

return {testing=testing}
```

**In my C# Winform:**
``` csharp
        private void Main_Load(object sender, EventArgs e)
        {
            _luaMain = new Lua();
            _lua = _luaMain.CreateEnvironment();
            ...          
        }

        private void btnShowRawData_Click(object sender, EventArgs e)
        {
            _luaMain = new Lua();
            _lua = _luaMain.CreateEnvironment();
            // create a Lua script environment (global)
            string path = @"Lua\\hello.lua";
            // run a chunk, first the code, than the name of the code
            dynamic v = _lua.DoChunk("local t = 10 + 3;  print('Hello World!'); return t;", "Test1");
            Console.WriteLine(v);
            using (StreamReader reader = File.OpenText(path))
            {
                string str = reader.ReadToEnd();
                reader.Close();
                dynamic r = _lua.DoChunk(str, "test2");
                Console.WriteLine(r);
            }
        }
```

**Comment by RussellHaley** [comment]
Any hints? 
I have no idea why this doesn't work and I haven't come across anything in the documentation yet. I was hoping to use https://github.com/Yonaba/Moses in my application?

**Comment by RussellHaley** [comment]
Ah, now I see. The comment in #67 was incomplete because the markdown removed the important part of the solution. The author used real chevrons and MD removed the chevrons and everything in between. Use "& lt ;" without the spaces to display greater than/less than.

~~_lua = _luaMain.CreateEnvironment();~~
_lua = _luaMain.CreateEnvironment&lt;LuaGlobal&gt;();

**Comment by neolithos** [comment]
Thx.

Glad to see that you found a solution. See also my comment on the issue #67.

The current implementation of LuaGlobal prints the output in the debug console. But you can inherit from LuaGlobal and override the print method.

Do get all to run?

**Comment by RussellHaley** [comment]
Thank you for asking, I did get it to work. I was able to load Moses and call the sum function on a table. I will ramp up and test more things as time permits.
