### ISSUE TITLE
Create Timer in C# which calls function in LUA

### ISSUE THREAD

**Issue by Symbai** [neolithos/neolua#82]
NeoLua Version:
1.3.0

I'm trying to add a timer to LUA which calls a function in the LUA script. So far everything works except that I dont know how to call the LUA function in my c# timer class.

The following example raises an exception on OnTimer?.Invoke(this) saying "'Nil' cannot be called"
OnTimer value on runtime is {Method = {Neo.IronLua.LuaResult Tick(System.Runtime.CompilerServices.Closure, System.Object)}}

Example to reproduce:
```
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            using (var lua = new Neo.IronLua.Lua())
            {
                dynamic dg = lua.CreateEnvironment();
                dg.createTimer = new Func<CustomTimer>(Awesome.createTimer);

                dg.dochunk(@"local timer = nil
local ticks = 0
local function Tick(timer)
	ticks = ticks + 1
	printf(ticks)
end
timer = createTimer()
timer.Interval = 100
timer.OnTimer = Tick
timer.Enabled = true");
            }
        }
    }

    public class CustomTimer
    {
        public CustomTimer()
        {
            timer.Elapsed += Timer_Elapsed;
        }

        private void Timer_Elapsed(object sender, ElapsedEventArgs e)
        {
            //how to raise OnTimer?
            OnTimer?.Invoke(this);
        }

        private Timer timer = new Timer();
        public double Interval
        {
            get => timer.Interval;
            set => timer.Interval = value;
        }
        public Func<object, object> OnTimer;
        public bool Enabled
        {
            get => timer.Enabled;
            set => timer.Enabled = value;
        }
    }

    public static class Awesome
    {
        public static CustomTimer createTimer()
        {
            return new CustomTimer();
        }
    }
```

**Comment by Symbai** [comment]
Head -> table...

After I did it just works. Do you think its possible to extend the exception messages with some more information that helps tracking down the issues? Can you maybe for example include the line number of the lua that causes the exception?

**Comment by neolithos** [comment]
You need to set the compile options. E.g.:
```C#
lua.CompileChunk("source code here", "test.lua", new LuaCompileOptions() { DebugEngine = LuaStackTraceDebugger.Default });
```

**Comment by Symbai** [comment]
Thanks and a last question, how would I end / dispose this timer in a second lua script?

**Comment by neolithos** [comment]
You declared the timer variable local, so the scope is only the first script.
You need to set it to a global variable.


```
timer = createTimer()
```

and run on the same environment `dg`.
```
timer.Enabled = false;
```

**Comment by Symbai** [comment]
Thanks again for your help!
