### ISSUE TITLE
NotImplementedException System.Byte

### ISSUE THREAD

**Issue by Symbai** [neolithos/neolua#86]
NeoLua Version: 1.3.2

Example to reproduce:
```
dg.printByte = new Action<string, byte>(LuaFunctions.PrintByte);
...
public static void PrintByte(string message, byte value) { ... }
```

```
printByte("Hi", 0x1)
```
Throws a NotImplementedException System.Byte

**Comment by neolithos** [comment]
I need more detail, because this little example works fine:
```C#
public static void PrintByte(string message, byte value)
	=> Console.WriteLine("{0}: {1}", message, value);

static void Main(string[] args)
{
	var l = new Lua();
	var g = new LuaGlobal(l);
	dynamic dg = g;
	dg.printByte = new Action<string, byte>(PrintByte);
	g.DoChunk("printByte('Hi', 0x1);", "test.lua");
}
```

**Comment by Symbai** [comment]
It was an issue not related to NeoLua and happened within PrintByte method but I got confused because the stacktrace told me issue was inside Neo.IronLua.LuaChunk.Run ... LuaChunk.cs.

**Comment by neolithos** [comment]
For development, it is the best to use a compile extension that can produce the Lua-StackTrace.

> e.g.: `LuaTraceLineDebugger`
> This one I developed, because the missing frames are a real pain.
