### ISSUE TITLE
Regex location match "()"

### ISSUE THREAD

**Issue by coldino** [neolithos/neolua#88]
I'm attempting to load an existing Lua codebase and came across an infinite loop in an XML parser due to this missing functionality.  It appears that an empty bracket pair in a regex should return the location within the string.

I'm no Lua expert and find the Lua docs very impenetrable, so have not been able to find if this is a standardised behaviour - but the original codebase runs on LuaJit just fine.

NeoLua Version:  Latest commit (a0fdcc68d0dbb).

Example to reproduce:
```Lua
> str = "hello"
> A,B,C = str:match("(e)(.)()")
> print(inspect({A,B,C}))
{ "e", "l", "" }
```

Expected output (from LuaJit):
```Lua
> str = "hello"
> A,B,C = str:match("(e)(.)()")
> print(inspect({A,B,C}))
{ "e", "l", 4 }
```

**Comment by neolithos** [comment]
It is confirmed, but I need to find a equivalent in the .net Regex-class.

**Comment by coldino** [comment]
The match result for an empty closure has an Index field.

**Comment by neolithos** [comment]
Are you able to give me more examples/test cases?

**Comment by neolithos** [comment]
The infiinite loop is related to the return of the match function. So, it is no suprise for me.

But I have also trouble to understand the regex.

It would be a great help, if you can split this up in handleable test cases.

**Comment by coldino** [comment]
Looking for references to this behaviour:
* [Post in lua-users](http://lua-users.org/lists/lua-l/2015-07/msg00518.html)
* [3rd-party Lua docs](https://www.fhug.org.uk/wiki/wiki/doku.php?id=plugins:understanding_lua_patterns#captures)

Bit worried by the lack of info.

**Comment by neolithos** [comment]
```
^%s*([^<]-)%s*<([%?/]?)([%w:]+)(.-)([%?/]?)>()
```
is translated to
```
^\s*([^<]*?)\s*<([\?/]?)([\w:]+)(.*?)([\?/]?)>()
```
Does some see the problem?
