### ISSUE TITLE
how to set winform value

### ISSUE THREAD

**Issue by SalsNET** [neolithos/neolua#90]
C#
var lua = new Lua();
var environment = lua.CreateEnvironment();
environment.RegisterPackage("winMain", typeof(MainClient));
environment.DoChunk(AppDomain.CurrentDomain.BaseDirectory + "scripts\\main.lua");
environment.CallMember("main");

Lua
function main ()
	winMain.Text = 'test1';
	return 'ok';
end

Exception
'MainClient:Text' not founud.

**Comment by neolithos** [comment]
Just set the reference not the type.
```C#
environment.winMain = new MainClient();
```

**Comment by SalsNET** [comment]
gooooood 
thanks
