### ISSUE TITLE
Floating point and culture issues

### ISSUE THREAD

**Issue by Symbai** [neolithos/neolua#91]
NeoLua Version: 1.3.2

There seems to be an issue with float values and culture specific formats. In the example below the float value of "value" parameter is different when used in different culture environments where dot and comma in values have a different meaning. Haven't tested but perhaps this issue also occur on decimal and double types.

Example to reproduce:
```
local a = 0.4
local b = 0,4
Dostuff(a)
Dostuff(b)

//C#
public static void DoStuff(float value) { ... }
```

On English culture value it will be:
a = 0.4
b = 0

On German culture value will be:
a = 0
b = 0.4

But both should be 0.4 otherwise scripts cannot be shared between people living in different countries.

**Comment by neolithos** [comment]
Lua parses language invariant. see Lua.Runtime.cs:428.

Your example produces on a german culture:
```
local a = 0.4;
local b = 0,4;
return a,b;

a = 0,4
b = 0
```
`b` must be zero, because the 4 assigned to nowhere.
