### ISSUE TITLE
Tables that contain a comment throw exception

### ISSUE THREAD

**Issue by xeropresence** [neolithos/neolua#92]
NeoLua Version: 1.3.2

Example to reproduce:
```
styles = {
        ["SubStyle"] = {
            [0] = "zoop",
		  --[1] = "removed",
        }
};
```

```
Lua _lua = new Lua();
_luaScriptz = _lua.CreateEnvironment();
_luaScriptz.DoChunk(aboveLuaCode,"text.lua");
```
Neo.IronLua.LuaParseException: 'Literal, function or table-ctor expected.' @ line 5.

If the comma after "zoop" is removed, a different exception is generated.

Neo.IronLua.LuaParseException: 'Unexpected token 'InvalidComment'. '}' expected.' @ line 4

Is this working as intended?

**Comment by neolithos** [comment]
It is working, how I implemented it. But it is not correct.
I will fix it.

**Comment by neolithos** [comment]
Thx.
