### ISSUE TITLE
string.format %q not supported? io.open 'w' option not functioning correctly?

### ISSUE THREAD

**Issue by RussellHaley** [neolithos/neolua#97]
NeoLua Version:
1.3.8

Hello, I'm using serpent serializer (https://github.com/pkulchenko/serpent) to write out a preferences table. It seems that the format specifier %q is not implemented? Also, note that I am specifying the open option of "write" but the file isn't being overwritten properly?

Example to reproduce:
```C#
            _lua.DoChunk(@"
            package.path = package.path .. '\\Lua\\'
           serpent = require 'serpent'
            if not serpent then 
                print('no serpent') 
                print(package.path)
            end
            f = io.open('preferences.lua','w')
            f:write(serpent.block(preferences))
            f:close()
                ", "save preferences");
```

preferences.lua before save:

```lua
preferences = 
{
	wakeup = 'WAKEUP_400_MHZ'
}

return preferences
```

preferences.lua after save:
```lua
{
  wakeup = %q
} --[[]] = 'WAKEUP_400_MHZ'
}

return preferences
```

The expected behaviour (as I am sure you are aware...) is that the file is entirely overwritten, not pre-pended.

Also I noted that the package.path output doesn't seem quite right:

```lua 
package.path = package.path .. '\\Lua\\'
print(package.path)
```
produces ```%currentdirectory%\Lua\```

Which I suppose could be a bug or a feature depending on how you look at it. ;-)

**Comment by RussellHaley** [comment]
Ah, I just found LuaTable.ToLson().

**Comment by neolithos** [comment]
These adresses two issues.

1.` %q` is not implemented. Needs to be done.
2. `w+` does not truncate the file. It looks like I exchanged the meaning.

And two features.
- `%currentdirectory%` is a feature. And should help resolve paths.
- `ToLson`, `ToJson`, `FromLson` and `FromJson` are nice helper.

For the first two points I try to find time in short term.

**Comment by RussellHaley** [comment]
Thank you, ToLson and FromLson is what I needed so I'm not bothered.

**Comment by neolithos** [comment]
I fixed the two issues. But I need  a test suite for `string.format`-function to make a whole rewrite.

**Comment by gfichter** [comment]
I don't think FileMode.Truncate is a good translation of Lua "w" mode, since it will not create a new file.  Wouldn't FileMode.Create be closer?

**Comment by neolithos** [comment]
@gfichter: After reread the lua documentation. I would use this configuration?
