### ISSUE TITLE
Possible to use require() without loading from the filesystem?

### ISSUE THREAD

**Issue by Drachenkaetzchen** [neolithos/neolua#99]
Hi,

I'm working on a project where I'd like to keep a required module in a Resource (resx). With MoonSharp, I can simply create a custom script loader.

Is something similar possible with neolua?

**Comment by neolithos** [comment]
Hi,
it is possible, you need to inherit from LuaGlobal and implement your own require logic.

```C#
public class MyLuaGlobal : LuaGlobal
{
...
	[LuaMember("require")]
	public LuaResult LuaRequire(object modname)
	{
...
	}
...
}
```

**Comment by Drachenkaetzchen** [comment]
Thank you :) I'll try it out soon.
